### ISSUE TITLE
Move Gradle out of beta

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10189]
**Description**

There are some corner cases while using Gradle quarkus tooling or the gradle file is not behaving well.

This issue is to collect the known "bigger" issues for info.

related: 
https://github.com/quarkusio/quarkus/pull/4905#issuecomment-546851800 
update documentation to have both maven and gradle variation

Definition of move Gradle out of beta (2020-05-20) 
Good parts:
  - we have tests
  - classloader isolated
Needed:
  - be a good gradle citizen (in/output)
  - devmode on run from ide
  - deployment/runtime mismatch (affects gradle more than maven)

## Epic items
(this section is auto-generated - manual edits will get lost)
- [x] [#3552](https://github.com/quarkusio/quarkus/issues/3552) [gradle] gradle test still not work
- [x] [#4960](https://github.com/quarkusio/quarkus/issues/4960) Building with Gradle gives a warning about CDI dependencies
- [x] [#4982](https://github.com/quarkusio/quarkus/issues/4982) Do not require Gradle to be installed to generate the Gradle wrapper
- [x] [#5204](https://github.com/quarkusio/quarkus/issues/5204) Gradle plugin does not work with plugins DSL
- [x] [#5488](https://github.com/quarkusio/quarkus/issues/5488) EntityManager in not injected when using devmode with gradle
- [ ] [#5539](https://github.com/quarkusio/quarkus/issues/5539) Multiple sourceDirs for Gradle are not supported.
- [x] [#5722](https://github.com/quarkusio/quarkus/issues/5722) Gradle plugin doesn't support multi module project well.
- [ ] [#5807](https://github.com/quarkusio/quarkus/issues/5807) [devtools] Add Gradle Kotlin DSL as another build tool option.
- [x] [#6035](https://github.com/quarkusio/quarkus/issues/6035) Pass Kotlin compiler plugin options to dev mode in Gradle
- [x] [#9046](https://github.com/quarkusio/quarkus/issues/9046) Improve gradle and maven test harness to give us more release confidence
- [ ] [#9490](https://github.com/quarkusio/quarkus/issues/9490) Deployment BOM is not enforced on the build classpath
- [x] [#9281](https://github.com/quarkusio/quarkus/issues/9281) Gradle build cache is not being leveraged

**Comment by emmanuelbernard** [comment]
Hey all, Please enlist to #5101 as it is the follow up actions post 1.6

**Comment by jskovjyskebankdk** [comment]
@emmanuelbernard  Would you consider including #9738 in the list?
Bootstrap (and thus unit testing with @QuarkusTest) does not work with Gradle.

**Comment by emmanuelbernard** [comment]
@jskovjyskebankdk yes that makes sense CC @glefloch

**Comment by glefloch** [comment]
Yes I'm still working on it, I will open a draft PR ASAP.

**Comment by 38leinaD** [comment]
I think https://github.com/quarkusio/quarkus/issues/11388 is essential for beginners to be able to use gradle safely. Without it Gradle users will experiencing problems that maven users have not seen before and thus might frustrate them quickly.

**Comment by AmsterdamFilho** [comment]
This was in the 1.7 roadmap, but it was missed.

What is the new expectation?

**Comment by JuanCamiloRada** [comment]
#13579 should be consider too as part of this ticket.

**Comment by julianseeger** [comment]
#2811 should be part of this. Quarkus+Gradle+Kotlin=fail

**Comment by glefloch** [comment]
Should we consider moving gradle out of beta for Quarkus 2.0 ?

**Comment by aloubyansky** [comment]
I think we should review the current state and what's missing for that.
Let's get the call conditional deps in first though.

**Comment by postol** [comment]
Hi,

is there any plan to move this out of beta? As it is currently blocking jib extension for GraalVM for gradle - see here: https://github.com/GoogleContainerTools/jib-extensions/issues/72

**Comment by chanseokoh** [comment]
>? As it is currently blocking jib extension for GraalVM for gradle - see here: [GoogleContainerTools/jib-extensions#72](https://github.com/GoogleContainerTools/jib-extensions/issues/72)

@postol sorry, I spread misinformation in GoogleContainerTools/jib-extensions#72. Jib already has a Quarkus extension for Gradle, and #72 has nothing to do with Quarkus. I updated #72 accordingly.

**Comment by maxandersen** [comment]
thanks for clarifying @chanseokoh.
