### ISSUE TITLE
Track JDK WARNING:Illegal statements to be fixed in quarkus or in upstream libraries

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10271]
### Description

This issue tracks libraries that need to fix some now considered abusing use of the OpenJDK classes.

A typical example

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (jar:file:/Users/emmanuel/.m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar!/) to constructor java.util.AbstractCollection()
WARNING: Please consider reporting this to the maintainers of org.eclipse.yasson.internal.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/How.20to.20get.20rid.20of.20the.20ILLEGAL.20messages for some slightly more infos 

Essentially OpenJDK 11 went from not displaying to displaying once such error. With the intention to no longer run with such error in the future. Better start fixing things over time.

The strategy is to identify these issues one by one as we discover them and created a dedicated Quarkus issue for each linked back here in the epic list.
Then help upstream to fix things
In parallel, we could decide to mask these warnings for the issues we have identified and logged (and remove the masking when they are supposedly fixed).

Note that running with `--illegal-access=debug`,  will print the warnings on every illegal access that occurs during the run. Which would be a more effective way to find all culprits.

## Epic items
(this section is auto-generated - manual edits will get lost)
- [ ] [#9726](https://github.com/quarkusio/quarkus/issues/9726) WARNING: An illegal reflective access operation has occurred
- [ ] [#10273](https://github.com/quarkusio/quarkus/issues/10273) Upgrade Yasson to a version not raising JDK warnings
- [ ] [#10303](https://github.com/quarkusio/quarkus/issues/10303) Remove illegal refletive access warning for xstream

**Comment by maxandersen** [comment]
looks like Yasson issue fixed recently at https://github.com/eclipse-ee4j/yasson/issues/412\

**Comment by seseso** [comment]
I'm receiving some exception in DEBUG (not warning) on quarkus startup, witch I'm not sure if they are related to this but:

java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:233) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:227) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:112) ~[netty-transport-4.1.49.Final.jar!/:na]
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:77) ~[netty-transport-4.1.49.Final.jar!/:na]
	at io.quarkus.netty.runtime.NettyRecorder$1.run(NettyRecorder.java:28) ~[quarkus-netty-1.5.0.Final.jar!/:1.5.0.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3e7bc5e
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:558) ~[na:na]
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:347) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:338) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:112) ~[netty-transport-4.1.49.Final.jar!/:na]
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:77) ~[netty-transport-4.1.49.Final.jar!/:na]
	at io.quarkus.netty.runtime.NettyRecorder$1.run(NettyRecorder.java:28) ~[quarkus-netty-1.5.0.Final.jar!/:1.5.0.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by emmanuelbernard** [comment]
@seseso that one is a different story

**Comment by seseso** [comment]
Ok, so please ignore my comment. I'll search for it on other issues and
open a new one if necessary.

**Comment by aguibert** [comment]
@emmanuelbernard we may want to do a broader investigation to chase down the illegal access issues. Perhaps with `--illegal-access=debug`, which will print the warnings on _every_ illegal access that occurs during the run.

The default in JDK 11 is `--illegal-access=warn` which only prints the warning for the first illegal access, so fixing them all in this manner will be a bit of a whack-a-mole exercise.

**Comment by pschyma** [comment]
Don't know if this the right place, but since 1.5.x I see an illegal access warning from xstream when I run `./gradlew test`:
```
❯ ./gradlew test

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/peter/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
This is on JDK 11.

**Comment by emmanuelbernard** [comment]
@pschyma ah yes I saw this one to. Perfect place.

**Comment by emmanuelbernard** [comment]
@pschyma do you happen to know what your test was exercising when it happened?

**Comment by emmanuelbernard** [comment]
@aguibert ah yes, I did not want to scare people too fast ;)
