### ISSUE TITLE
Provide various installation mechanisms for quarkus cli

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#10354]
**Description**
Make Quarkus cli available from as many installation options as possible - at least those that are trivially done/maintained.

Provide a download of cli (a .zip) (osx/linux/windows)
- [ ] github release of quarkus-runner jar
- [x] enable sdk install quarkus (osx/linux) #18381 
- [x] enable brew install quarkus (osx)
- [ ] scoop install (windows)
- [x] jbang installer (already exists, but not automated)
- [ ] copr package (yum/dnf)
- [ ] debian package 
- [ ] enable chocolatey.org install (windows)

**Implementation ideas**
In https://jbang.dev I've implemented automatic generation of install scripts of all of the above except debian package. 

As long as we have a stable github release upload/naming mechanism that should be trivial to replicate.

**Comment by maxandersen** [comment]
jreleaser.org is a project by @aalmiray that formalizes a lot of the release mechanisms done for jbang. we should see if that could be used.

**Comment by cescoffier** [comment]
@gsmet @ebullient 

This issue was planned for Q1, but it seems to be mostly done. Is anything else still required?

**Comment by maxandersen** [comment]
closing as we have multiple ones now including windows. antyhing needed beyond that we open as individual issue.

**Comment by nitind** [comment]
Is there no mechanism that _doesn't_ require an installer of some kind?

**Comment by maxandersen** [comment]
@nitind what do you consider "not" an installer?

you can download the jar and run it manually if you prefer?

**Comment by nitind** [comment]
> @nitind what do you consider "not" an installer?
> 
> you can download the jar and run it manually if you prefer?

My mistake, I was going off a combination of comment 0 not having that box checked, the Maven quarkus-cli-3.9.5.jar not being standalone, and https://quarkus.io/guides/cli-tooling#installing-the-cli not mentioning this option.

**Comment by maxandersen** [comment]
@nitind gotcha - yeah we don't mention it as you'll need some script and something added to the path anyway to make it usable. that's basically what jbang handles for you in the simplest setup.

we could mention using the .jar directly if you think it helps some usecase?
