### ISSUE TITLE
Support for Mandrel

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#10367]
### Description
Mandrel should be usable with Quarkus since Mandrel is more or less a dropin replacement of graalvm ce we don't expect much conflicts but there are a few things to ensure.

- [ ] check mandrel will jjust work by setting GRAALVM_HOME to root of mandrel based jdk
- [ ] have the debug features of graalvm/mandrel exposed as a flag
- [ ] have a way to use mandrel when doing quarkus native build via containers.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

**Comment by Karm** [comment]
@maxandersen This is resolved :smiley:
