### ISSUE TITLE
Upgrade to MicroProfile 4.0

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#10522]
### Description
Support MicroProfile 4.0

## Epic items
(this section is auto-generated - manual edits will get lost)
- [x] [#10514](https://github.com/quarkusio/quarkus/issues/10514) Upgrade to MP Metrics 3.0
- [x] [#10515](https://github.com/quarkusio/quarkus/issues/10515) Upgrade to MP OpenAPI 2.0
- [x] [#10516](https://github.com/quarkusio/quarkus/issues/10516) Upgrade to MP JWT 1.2
- [x] [#10517](https://github.com/quarkusio/quarkus/issues/10517) Upgrade to MP Config 2.0
- [x] [#10518](https://github.com/quarkusio/quarkus/issues/10518) Upgrade to MP Health 3.0
- [x] [#10519](https://github.com/quarkusio/quarkus/issues/10519) Upgrade to MP Fault Tolerance 3.0
- [x] [#10520](https://github.com/quarkusio/quarkus/issues/10520) Upgrade to MP Rest Client 2.0
- [x] [#10521](https://github.com/quarkusio/quarkus/issues/10521) Upgrade to MP OpenTracing 2.0
- [x] [#15970](https://github.com/quarkusio/quarkus/issues/15970) Upgrade Reactive Rest Client to MP Rest Client 2.0

**Comment by tobiasstadler** [comment]
Afaik SmallRye Reactive Messaging will support MP 4 with version 3 which uses/requires vert.x 4. Will the Upgrade have to wait until Quarkus uses vert.x 4?
