### ISSUE TITLE
Quarkus "2.0" - vert.x 4

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#14779]
### Description
upgrade to vert.x 4 (#14685) are going to have an impact on a lot of extensions, but somewhat minimal on user code.

Thus we started referring to that work as Quarkus 2 and want to capture the impact and what changes it requires. 

Note: this is very much work in progress - working to minimize impact.

Embedded Integration issues:
  - [x] JSON 
    - [x] The new JSON support is requiring JSON classes to be initialized at runtime, it degrades the native executable startup time We need a clean separation with Jackson 
     - [x] byte[] support seems to have been lost, The JSON decoding does an instanceOf Buffer, which would not work for the generated API
     - [x] Fix Base64Encoding using the encoder from JSONUtils
     - [x] The Jackson extension should provide the mapper to Vert.x - https://github.com/quarkusio/quarkus/issues/15031
- [x] Event Loop does not execute task with the captured TCCL, solution: use upcoming ThreadFactory and WorkerFactory features, as well as the ability to retrieve the `Context` from an HTTP request.
- [x] OAuth The current Quarkus code is using internals which have moved or disappeared
        Work In Progress: reduce the dependency of the security layer from Vert.x. (happend due to use of internal vert.x - quarkus to change)
- [x] Re-enabled OIDC integration tests - https://github.com/quarkusio/quarkus/issues/15084
- [x] Metrics https://github.com/eclipse-vertx/vert.x/issues/3732
- [x] Q Metrics to use updated HTTP API (enhancement): #14905
- [x] HttpServerRequest attributes https://github.com/eclipse-vertx/vert.x/issues/3579

Bugs:
- [x] PGClient now throwing java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: { "message": "argument of LIMIT must be type bigint, not type text", "severity": "ERROR", "code": "42804", "position": "272", "file": "parse_coerce.c", "line": "1205", "routine": "coerce_to_specific_type_typmod" } after a Hibernate filtered query.
- [x] Mailer format change, all mail were multiformat, in vert.x 4 now sends simple or multiform dependent on content [fixed](https://github.com/vert-x3/vertx-mail-client/pull/162)
 
Big blast radius:
- [x] #14870 Router matching with two  "/foo" / "/foo/*" separate routes do not match the same way anymore
- [x] Quarkus `@Route` API change required by change of HttpMethod from enum to interface. This will impact all extensions that use `@Route` to declare extension-provided endpoints. Suggestion: Introduce deprecation cycle in 1.x and have quarkus owns annotation to decouple from vert.x api. For reference, required changes are [here](https://github.com/quarkusio/quarkus/pull/14868/commits/0b843f113adac7528539e7321cdf21c5144ffe85)

**Comment by pmlopes** [comment]
@maxandersen I've a few remarks to this issue:

1. JSON `byte[]` support isn't gone. In fact, it has been enhanced. In vert.x 3.x the JSON object would not store `byte[]` internally because `byte[]` isn't a valid JSON type. Instead, `byte[]` data would be converted to a `String` base64 representation. This has a few drawbacks such as too much encode/decode cycles and unneeded gc. In vert.x 4 JSON objects have been enhanced to avoid this encoding/decoding, plus besides `byte[]` support which was availabe as: `{add|get}Binary()` you now have also: `{add|set}Buffer()` to handle vert.x Buffer type. If you were using the `getBinary/setBinary` to handle `byte[]` then your application should just work like before. Apparently, you were relying on the fact that `byte[]` gets converted to string on the setter. If you want that behavior, you still can. But now you need to use the right getter, `getString()` which will convert binary data `byte[]/Buffer` to base64 string.

2. Router `/*` seems to still match, the test passes:

```java
  @Test
  public void testSimpleNotNeededWildcard() throws Exception {
    router.route("/*").handler(rc -> rc.response().end());
    testRequest(HttpMethod.GET, "/", 200, "OK");
  }
```

3. Regarding Oauth2, please note that, many features from `vert.x 4` were back ported to the 3.9 branches to address a few requirements for Quarkus. The backports had to reflect the internal code structure of 3.9, perhaps you could describe what were you missing, and I may try to assist you to find the new public API way of doing it.

**Comment by vietj** [comment]
A few extra remarks:

1. Using Netty event-loop does not propagate TCCL, but that is very expected. In fact Netty event-loop implementation is final and cannot be overriden to provide add such behavior. This is working with Vert.x 3 because Vert.x 3 will not unset previous TCCL when executing a task and this has been corrected in Vert.x 4 . If Quarkus code is using Netty event-loop directly it actually has to do TCCL dance because there is nothing Vert.x can do here
2. we can examine the Jackson initialization and mitigate the effect. Here I need to remain that the changes that were introduced (also in Vert.x 3) have been done on Quarkus demand because Quarkus was using something else than Jackson and we have been asked the ability to run Vert.x without Jackson. Now that Quarkus is actually using Jackson (for a reason I ignore because it is not a spec...) we cannot rollback to simply using Jackson as this would be a breaking change. So we need a precise description of the item and see how we can make this Quarkus friendly

**Comment by sberyozkin** [comment]
Hi Paulo, my current plan is to try and complete the migration to Vert.x Mutiny Web Client, please see #14492. I've already completed the first phase (no actual migration but only encapsulating all the Vert.x OAuth2 code in a single class). Note I may still end up pleading for help with the migration to the new Vert.x 4.0 OAuth2 code if I fail with this migration :-), but for now I hope it will give us more control around some specific OIDC decisions without having to affect Vert.x 4.0 OAuth2. I'll see how it goes.
Cheers, Sergey

**Comment by cescoffier** [comment]
@vietj about 2. We need a clear separation between Vert.x and Jackson. What was introduced in 4 make Jackson in the call tree if you don't have any Json support (which can be the case). A solution would be to have the SPI you have implemented for Jackson and delivered optionally (in another module), so we are sure it's not in the call tree.

**Comment by cescoffier** [comment]
@pmlopes I can see the improvements, however, it's breaking on our side. I now need to do things like this before sending the JSON Object to Resteasy:

```
Map<String, Object> map = new HashMap<>();
for (Map.Entry<String, Object> entry : json.getMap().entrySet()) {
    if (entry.getValue() instanceof byte[]) {
        map.put(entry.getKey(), Base64.getEncoder().encodeToString((byte[]) entry.getValue()));
    } else {
        map.put(entry.getKey(), entry.getValue());
    }
}
```

**Comment by ebullient** [comment]
RE: eclipse-vertx/vert.x#3579
Stuart and I opened that because we had to do stupid things to keep track of context as Rest traffic went through Vert.x to make sure metrics could be recorded at completion time w/ a decent resolved path.
In that issue, you commented Vert.x 4 should aready support keeping context in the attribute, but you also offered to provide more/similar context to Metrics support that you do for Tracing (specifically requestRouted). 
So there is some work I can do once we have a compiling Vert.x 4 branch to remove some of the awkwardness we have and use the HttpServerRequest more directly.. but giving the metrics the same amount of context that tracing has would also be useful/better.

w.r.t. eclipse-vertx/vert.x#3732
The Metrics API changed to drop the response parameter. Yes, it is possible for implementors to store the response if needed (which I did immediately), but the change seemed somewhat odd/unnecessary, given you still have the response in hand.

**Comment by maxandersen** [comment]
> @maxandersen I've a few remarks to this issue:

thx - I made the list based on issues highlighted by @cescoffier to have it captured. I'll let him and @ebullient comment on the specifics.

**Comment by geoand** [comment]
> @vietj about 2. We need a clear separation between Vert.x and Jackson. What was introduced in 4 make Jackson in the call tree if you don't have any Json support (which can be the case). A solution would be to have the SPI you have implemented for Jackson and delivered optionally (in another module), so we are sure it's not in the call tree.

I'll start looking at this tomorrow to see how I can help

**Comment by ebullient** [comment]
Created a comment in the current Vert.x PR with stashed build logs for reference (as a point in time cut): https://github.com/quarkusio/quarkus/pull/14685#issuecomment-773631093 
Specifically of use here are the logs for panache with the postgres client
We also have a native failiure w/ GraphQL (an NPE reading JSON from a WebSocket is suggested by the stack)

**Comment by geoand** [comment]
@cescoffier which tests should I be looking to see the problems with Jackson?

**Comment by pmlopes** [comment]
@ebullient @cescoffier can you point me to a test that is failing due to the `*` "missing" in the route. This issue requires a further investigation from my side as

https://gist.github.com/pmlopes/553e49217b0784b55f4b8c1a2760fdcc

Seems to yield the "expected" result on 3.9.5, 4.0.0, 4.0.1 and master. So I'm assuming that the issue is probably something else and adding a `*` just triggers a side-effect that "fixes" it.

**Comment by ebullient** [comment]
I'm creating a new branch to rebase on the fresh vertx snapshot.. and I'll.. "unfix" one of the places so you can see the failure. give me a few minutes..

**Comment by ebullient** [comment]
https://github.com/quarkusio/quarkus/pull/14868 -- I've created a new draft PR pointing to a branch that has a digested view of the changes @cescoffier and I have attempted this far.

I'm currently running additional tests (to make sure I know what is/isn't broken). I'll create individual issues against that branch with instructions for how to recreate the failure. I'll update the checklist at the top to reference each issue.

@pmlopes -- The key for you jumping ahead will be undoing this "Matching of prefixed routes" commit. It may be that you'll have a clear idea for how to recreate it if you look at what we changed.

**Comment by vietj** [comment]
@ebullient I added support for getting the request context with this commit https://github.com/eclipse-vertx/vert.x/issues/3792

**Comment by cescoffier** [comment]
@vietj Can you point me to the PR? I can't find it.

**Comment by geoand** [comment]
> @cescoffier which tests should I be looking to see the problems with Jackson?

@cescoffier ☝️ :)

**Comment by vietj** [comment]
@cescoffier it was merged in master as it is very small

**Comment by cescoffier** [comment]
@vietj can you link the commit?

**Comment by vietj** [comment]
@ebullient I tried reproducing the SQL client issue locally by forking the new draft PR you did and I'm not able to reproduce it. The draft PR CI also does not seem to reproduce it (https://github.com/quarkusio/quarkus/pull/14868), can you investigate and double check whether it still happens or not ?

**Comment by vietj** [comment]
@cescoffier here is the issue https://github.com/eclipse-vertx/vert.x/issues/3792 - the commit is linked from this issue

**Comment by vietj** [comment]
@geoand are you handling the Jackson issue ?

**Comment by cescoffier** [comment]
@geoand I think it was `jpa-without-entity`, basically something that needs Vert.x but that does not have Jackson in the classpath.

**Comment by cescoffier** [comment]
@vietj the SQL client issue is the Panache / PostgreSQL issue? I had the issue in `integration-tests/hibernate-reactive-postgresql`

**Comment by cescoffier** [comment]
> here it is eclipse-vertx/vert.x@2d8fc42

With this, we can simplify the RESTEasy Reactive TCCL issue.

**Comment by geoand** [comment]
> @geoand are you handling the Jackson issue ?

I am goign to start looking at it as at the moment I don't know exactly what the issue is TBH

**Comment by vietj** [comment]
@geoand ok

**Comment by vietj** [comment]
@cescoffier can you clarify which module I should run for the SQL client issue ?

**Comment by vietj** [comment]
I ran https://github.com/quarkusio/quarkus/pull/14868 provided by @ebullient and the issue does not appear here, what am I missing ?

**Comment by vietj** [comment]
I was able to reproduce the PostgreSQL issue and it seems that the issue is in Hibernate or Panache, here is the faulty SQL rejected by PostgreSQL:

```
select person0_.id as id1_16_, person0_.address_id as address_5_16_, person0_.name as name2_16_, person0_.status as status3_16_, person0_.uniqueName as uniquena4_16_ from Person2 person0_ where person0_.status = 'LIVING' and person0_.name = $1 order by person0_.id limit $1
```

here it should be instead

```
select person0_.id as id1_16_, person0_.address_id as address_5_16_, person0_.name as name2_16_, person0_.status as status3_16_, person0_.uniqueName as uniquena4_16_ from Person2 person0_ where person0_.status = 'LIVING' and person0_.name = $1 order by person0_.id limit $2
```

**Comment by geoand** [comment]
@cescoffier I am not sure I understand what the problem with Jackson and Vert.x 4 is.

Are you saying that where previously the `ObjectMapper` used by Vert.x 3.9.x was initialized at static-init, now it's initialized at runtime-init (when Jackson is present of course)?
I don't see that being the case TBH.

What I do think needs to be changed with regards to your substitutions is:

```java
@TargetClass(className = "io.vertx.core.json.Json", onlyWith = JacksonMissingSelector.class)
final class Target_io_vertx_core_json_Json {

    @Substitute
    public static io.vertx.core.spi.JsonFactory load() {
        io.vertx.core.spi.JsonFactory factory = ServiceHelper.loadFactoryOrNull(io.vertx.core.spi.JsonFactory.class);
        if (factory == null) {
            factory = new JsonFactory() {
                @Override
                public JsonCodec codec() {
                    return null;
                }
            };
        }
        return factory;
    }
}
```

should be:

```
@TargetClass(className = "io.vertx.core.json.Json", onlyWith = JacksonMissingSelector.class)
final class Target_io_vertx_core_json_Json {

    @Substitute
    public static io.vertx.core.spi.JsonFactory load() {
        io.vertx.core.spi.JsonFactory factory = ServiceHelper.loadFactoryOrNull(io.vertx.core.spi.JsonFactory.class);
        if (factory == null) {
            factory = new JsonFactory() {
                @Override
                public JsonCodec codec() {
                    return new JacksonCodec(); //this is the non-databind codec
                }
            };
        }
        return factory;
    }
}
```

**Comment by ebullient** [comment]
> I ran #14868 provided by @ebullient and the issue does not appear here, what am I missing ?

I didn't get all of the new items opened on Friday, and I try to do the best I can to take a break from work on the weekends. So I'll keep opening topic issues today (and will bring relevant comments over in that case).

**Comment by vietj** [comment]
@ebullient never mind, I've been able to reproduce see my other comment about issue with hibernate reactive / panache issuing incorrect queries

**Comment by vietj** [comment]
@ebullient I think we should have somebody from hibernate reactive look at the actual Postgres issue

**Comment by pmlopes** [comment]
@ebullient @cescoffier this PR https://github.com/vert-x3/vertx-web/pull/1865 will address the use of `/*` on sub routers and will bring back the 3.x behavior.

The current PR solves an offset calculation bug and relaxes the `/` rules for wildcard paths.

**Comment by ebullient** [comment]
> @ebullient @cescoffier this PR [vert-x3/vertx-web#1865](https://github.com/vert-x3/vertx-web/pull/1865) will address the use of `/*` on sub routers and will bring back the 3.x behavior.
> 
> The current PR solves an offset calculation bug and relaxes the `/` rules for wildcard paths.

Cool! To be clear, does that mean we would be able to back-out that commit when we move to a build w/ that fix?

**Comment by pmlopes** [comment]
@ebullient yes. All the commit https://github.com/quarkusio/quarkus/pull/14868/commits/979b1ea2ecf322c848c76468ffffb410c59c635c should be reverted.

**Comment by cescoffier** [comment]
@geoand I believe I tried that. The problem is that we have neither Jackson nor Databind in the classpath, and in this case we need to still be able to build and run in native. Having static blocks initializing the mapper is leading to build issues, at least as far as I can see, and we can't substitute it. 

Ideally, we would not need any substitutions at all, as it binds Quarkus to a specific version. To achieve this, we need to separate the vertx and Jackson more cleanly. Again, ideally, vertx core would not touch Jackson directly, and we would implement the SPI if we have the Jackson extension, otherwise we would just throw UnsupportedOperationExceptions.

Also, in my hack I had to declare class at runtime. It would be great to avoid that.

**Comment by geoand** [comment]
I'll check again, but I believe that I had no issue when running native image with or without Jackson Databind on the classpath

**Comment by cescoffier** [comment]
@geoand  With build time initialization of the JSON classes? Because if you delay the initialization at runtime yes, it works, but we want to avoid that.

**Comment by geoand** [comment]
I didn't change anything regarding initialization, so I had whatever the branch had.
I'll look into it again tomorrow morning

**Comment by cescoffier** [comment]
That's why it works... do make progress I moved the initialization at runtime, but we need to change that.

**Comment by geoand** [comment]
Understood, thanks for the background info

**Comment by geoand** [comment]
I just tried it: 

I removed all the Json related subtiturions in the Vert.x extension, while also removing the runtime initialization you added and everything worked as expected when jackson databind exists on the classpath and when it does not.

Do you want me to push the changes to the branch?

**Comment by ebullient** [comment]
I am ok with a force-push if you just want to clean it up and not leave remnants. We have the old vert.x branch for history if we need it.

**Comment by cescoffier** [comment]
I'm curious, as Jackson is in the call tree, so how does it handle its absence?

**Comment by geoand** [comment]
Jackson **core** is still necessary - it's just that Jackson **Databind** is not.
From a Quarkus perspective that is the same we have with Vert.x 3. We didn't want to bring in Jackson Databind as it is huge.

Vert.x 4 properly detects the presence or absense of Jackson Databind and adapts its json behavior accordingly. This detections is done in `static-init` so it works properly in GraalVM without us needing to substitute anything

**Comment by vietj** [comment]
@gavinking @FroMage ping on https://github.com/quarkusio/quarkus/issues/14779#issuecomment-775091870

**Comment by geoand** [comment]
We discussed the Json situation with @cescoffier and arrived at the following:

1) Based on what was described above, remove the substitutions and the runtime initialization of the Json related classes should get us in exactly the same situtation we have with Vert.x 3.9 and Quarkus - that is we exclude Jackson Databind and things continue to work. I have ran some tests and they all passed, Clement will also run some to verify.
2) As we really want users of Quarkus to have Vert.x use the same ObjectMapper as they have configured via Quarkus (or the equivalent with Jsonb), we will need to implement our own `io.vertx.core.spi.JsonFactory`. 
In this vein, ideally we would want `io.vertx.core.json.jackson.DatabindCodec` to have a configurable `ObjectMapper`, otherwise we need to just copy-paste the code into our own implementation.

**Comment by FroMage** [comment]
@vietj that looks indeed like bogus SQL, what test is causing this?

**Comment by cescoffier** [comment]
@FroMage `/integration-tests/hibernate-reactive-postgresql`. It's the test that uses `@Filter`.

**Comment by FroMage** [comment]
OK, so the query from the user's PoV is `SELECT FROM Foo` we have the following filters defined:

```java
@FilterDef(name = "Person.hasName", defaultCondition = "name = :name", parameters = @ParamDef(name = "name", type = "string"))
@FilterDef(name = "Person.isAlive", defaultCondition = "status = 'LIVING'")
@Filter(name = "Person.isAlive")
@Filter(name = "Person.hasName")
```

and the Panache layer calls:

```java
        jpaQuery.setMaxResults(maxResults);
...
            Filter filter = em.enableFilter(entry.getKey());
            for (Entry<String, Object> paramEntry : entry.getValue().entrySet()) {
                filter.setParameter(paramEntry.getKey(), paramEntry.getValue());
            }
            filter.validate();
```

So we don't control the limit parameter index, and we pass filter params by name, therefore: not our bug. I'll file an HR bug.

**Comment by vietj** [comment]
thanks @FroMage

**Comment by cescoffier** [comment]
About the JSON thingy, @geoand and I did have another look this afternoon, and our morning plan did not work. But we were able to move the required substitutions and runtime initialization to the undertow extension, so most applications would not see the penalties.

**Comment by vietj** [comment]
@maxandersen  we should keep track of the `VertxThreadFactory` that was an initial contribution to Vert.x 3 and ported to Vert.x 4 that is slightly different. The change is trivial but we should record here. See https://github.com/eclipse-vertx/vert.x/pull/3800

**Comment by FroMage** [comment]
The HR bug is fixed.

**Comment by vietj** [comment]
the mail format change has been addressed by https://github.com/vert-x3/vertx-mail-client/pull/162

**Comment by cescoffier** [comment]
Integration done.
