### ISSUE TITLE
Remove uberJar parameter from Maven mojos/goals in 1.13

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#14878]
**Description**
[As agreed on the mailing list](https://groups.google.com/g/quarkus-dev/c/CM7_La611Bw), the `uberJar` parameter in `QuarkusBootstrapMojo` (`BuildMojo` and `GenerateCodeMojo` respectively) should not be used anymore.
Instead, `quarkus.package.type=uber-jar` shall be used, as already documented: https://quarkus.io/guides/maven-tooling#uber-jar-maven

**Implementation ideas**

- [x] log a warning in the mojos (#14886)
- [x] remove remaining usages (#14886)
- [x] remove usages in quickstarts, if any (none)
- [x] @glefloch: deprecate and log a warning in the gradle plugins (#14899)
- [ ] remove the parameter in 1.13 (#14987)

**Comment by glefloch** [comment]
@famod we can also set this param in gradle plugin such as `gradle quarkusBuild -PuberJar`. I guess this should also be removed no? I can handle the gradle part.

**Comment by famod** [comment]
@glefloch I think this makes sense! We first need to deprecate it and log a warning to give users time until it is removed in 1.13.
If all goes to plan I'll create a PR later today for the Maven part. So if you would cover the Gradle part that would be great! Thanks!

**Comment by famod** [comment]
@glefloch FYI, #14886 deprecates the mojo parameter and logs a warning.
