### ISSUE TITLE
Implement Conscious Language Program

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#15580]
### Description
This epic covers all the work required to implement conscious language within the Quarkus project. 

See here for the 'what' and the 'why': https://github.com/conscious-lang/conscious-lang-docs/blob/main/faq.md

### Analysis
Initial analysis of the Quarkus main codebase shows:

    git clone git@github.com:quarkusio/quarkus.git && cd quarkus
    grep -ir blacklist . | wc -l
      15
    grep -ir whitelist . | wc -l
      11
    grep -ir master . | wc -l
     450
    grep -ir slave . | wc -l
      17

There might be some tooling available now to do a smarter search within codebases on GitHub. For example, looking for common variations of problematic language (e.g. 'black-list', 'black list', 'black_list', etc).

GitHub's info on renaming 'master' branch: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

### Tasks

Code Changes
- [ ] Replace all occurrences of problematic language in https://github.com/quarkusio/quarkus/
- [ ] Replace all occurrences of problematic language in https://github.com/quarkusio org
- [ ] Review occurrences in the [Quarkiverse GitHub org](https://github.com/quarkiverse), and create follow-up actions. 

Branch name changes
- [ ] Review impact of renaming all https://github.com/quarkusio 'master' branches to 'main'
- [ ] Rename all https://github.com/quarkusio 'master' branches to 'main'

**Comment by paulrobinson** [comment]
@gsmet I've made a start adding the task list for the branch name changes. But, I assume you will want to flesh that bit out. I'll work on the 'code changes' task list.

**Comment by gsmet** [comment]
@paulrobinson I think we are in a good place regarding this now? Could we close it?

**Comment by paulrobinson** [comment]
@gsmet I agree. We've changed what we can, and removed roughly 70% of the problematic language across the Quarkus repos. I can provide a more detailed analysis if needed. But in general the remaining occurrences are from public APIs in 3rd party libraries and seemingly benign cases (e.g. master key).
