### ISSUE TITLE
Vert.x 4.1 Epic

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#16955]
### Description
This issue is an umbrella issue referencing the various Vert.x issues that would need to be fixed or mitigated in Vert.x 4.1

### Issues

- [x] #16430 
- [x] #16338 
- [x] #16444 
- [x] #16453 
- [x] https://github.com/eclipse-vertx/vert.x/issues/3926 (alias support for certs)
- [x] https://github.com/eclipse-vertx/vert.x/issues/3970 (password per key)
- [x] https://github.com/eclipse-vertx/vert.x/issues/3969 (fail on missing alias)

CC @vietj @tsegismont

**Comment by vietj** [comment]
#16338 can be checked as it is closed

**Comment by tsegismont** [comment]
#16430 can be checked as it is closed

**Comment by vietj** [comment]
note the Vert.x issue related to #16453 has been merged in master and shall supposedly fix the issue

**Comment by vietj** [comment]
eclipse-vertx/vert.x#3926 has been fixed in master and will be part of 4.1.0.CR1 release

**Comment by cescoffier** [comment]
All good! Let me keep this issue open until we get Vert.x 4.1.0.Final integrated.

**Comment by tsegismont** [comment]
@cescoffier the fixes for the two oustanding issues have been merged and will be present in 4.1.1

**Comment by cescoffier** [comment]
I just merged the update to 4.1.1.

**Comment by geoand** [comment]
Closing this as Quarkus is now on `4.1.2`
