### ISSUE TITLE
Reactive Messaging (Kafka) - Kafka Checkpointing

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21437]
### Description

Extend reactive messaging to support offset checkpointing and potentially state reload. 

- [x] Commit & Failure SPI in Reactive messaging https://github.com/smallrye/smallrye-reactive-messaging/pull/1838
- [x] Checkpointing commit handler & State store APIs 
- [x] State store implementations Redis, Infinispan

**Comment by cescoffier** [comment]
@ozangunalp isn't that done (at lest partially)?

**Comment by ozangunalp** [comment]
The first step is merged. I nearly finished the second along with the redis state store implementation.

**Comment by cescoffier** [comment]
_update_: Almost there :-D

**Comment by cescoffier** [comment]
And .... ..... ..... DONE! Awesome work @ozangunalp !
