### ISSUE TITLE
Switch from distroless to micro

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21557]
### Description

The distroless approach we are using at the moment is very experimental and may lead to unexpected issues (like broken linking). Only experienced users should use this approach. Recently a new compatible runtime image has been produced which would avoid these issues. The size difference between both approaches is relatively minimal (and will prevent a lot of headaches). The objective of this epic is to:

1. Remove the generated distroless docker file 
2. Update the -native one to use this new image
3. Update the quickstart to use that new image
4. Update the documentation to mention this new image and make sure that distroless is marked experimental

### Battle Plan

* [ ] - Remove the generated distroless docker file  and Update the -native one to use this new image
* [x] - Update the documentation to mention this new image and make sure that distroless is marked experimental
* [x] - Update the quickstart to use that new image

**Comment by gsmet** [comment]
@cescoffier is it done?

**Comment by gsmet** [comment]
Looks like it's not done yet. If we get rid of distroless, we can also close https://github.com/quarkusio/quarkus/issues/21573 .

**Comment by cescoffier** [comment]
Not everything is done. I will have a look to complete it once back.
