### ISSUE TITLE
Improve extension author guide

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2277]
- [ ] Describe where to put APIs (runtime, deployment etc?)
- [ ] Describe where Substitutions and templates should live
- [ ] Dealing with META-INF/services files https://github.com/quarkusio/quarkus/issues/2299
- [ ] Offer a getting started section to ease the entry into Extension writing https://github.com/quarkusio/quarkus/pull/2406

**Comment by emmanuelbernard** [comment]
See also https://github.com/quarkusio/quarkus/pull/2406 for an easier guide start

**Comment by cmoulliard** [comment]
Here is a new list of things to be improved after spending 2 days to try to create a simple Servlet Extension - https://github.com/cmoulliard/quarkus-my-ext

To Do

- [ ] Update the maven archetype to create an extension as it is outdated
- [ ] Review Guide in order to avoid to have to create the extension under the quarkus/extensions project
- [ ] Add Junit test to show how to test deployment/runtime code
- [ ] Explain which BOM o be used and dependencies to include to register servlet, ... on undertow
- [ ] Explain when we must use @Recorder, @record
- [ ] Better introduce the role of the `deployment` and runtime` module, how the code is build and next used by a Quarkus application
- [ ] Do we need the runtime module for all the extensions ? If yes -> Why and when we should use it
