### ISSUE TITLE
Improve Mongo support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24749]
### Description
This epic is about improving the mongo support is Quarkus

### Analysis

- [ ] Extends / Align the reactive and imperative API
- [ ] Makes sure the back-pressure based on batch is implemented correctly
- [ ] Expose and use the new DNS SPI
- [ ] Document how to use Atlas and Atlas Serverless

**Comment by cescoffier** [comment]
No, not yet. Feel free to create them.

**Comment by evanchooly** [comment]
I was hoping to understand them so I could potentially work on them.  :)

**Comment by cescoffier** [comment]
Which one? They looks self-explanatory :-)

**Comment by evanchooly** [comment]
@cescoffier so using the DNS SPI, we can more your logic [here](https://github.com/quarkusio/quarkus/pull/23585) to a `DnsClientProvider` and retire the substitution, yes?

**Comment by cescoffier** [comment]
In theory, yes 😉

**Comment by cescoffier** [comment]
Unfortunately, we would need someone with deep experience with the Mongo driver. 

The driver is getting updated too that will require several changes on our side.

Also, how we deal with stream in the 'reactive facade' is suboptimal as we switch to the event loop thread for every item instead of trying to batch.
