### ISSUE TITLE
Some Redis improvements

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24750]
### Description
The Redis extension needs to be more aligned with the rest of Quarkus, and also should extend its API to allow more advanced use cases.

### Analysis

- [X] Expose the complete Redis API - https://github.com/quarkusio/quarkus/pull/26268
- [X] Allow using Redis custom commands  - https://github.com/quarkusio/quarkus/pull/26268
- [X] Test and document pub/sub - https://github.com/quarkusio/quarkus/pull/26268
- [X] Add support for sentinel and other topologies  - https://github.com/quarkusio/quarkus/pull/26268
- [X] Make sure the current extension covers the full set of features as exposed by Lettuce or Redisson. - https://github.com/quarkusio/quarkus/pull/26268
- [X] Add support for the probabilistic data structures and commands from redis labs - #28346 
- [X] Add support for the json commands from redis labs #28169 
- [x] Add support for the graph commands from redis labs - #28623 
- [x] Add support for the search commands from redis labs - #29081 
- [x] Add support for the time series commands from redis labs - https://github.com/quarkusio/quarkus/pull/29615

Will be done outside of this epic:
- Add the possibility to pre-load data into Redis - #29086 
- Investigate a Redis with Panache approach
- Add support for streams (stream commands)
- Add support for non-mono-typed hashes

**Comment by pmlopes** [comment]
@cescoffier I played around with the latest redis stack (7.0.0) which includes redis + a set of widely used extensions and generated this:

https://github.com/vert-x3/vertx-redis-client/blob/35da145298e55a1deae033cd0c53128c59e06cc2/src/main/java/io/vertx/redis/client/RedisStack.java

I'm not sure if this would make it easier for you to use on quarkus and mutiny. The main difference from before is that we're using `varargs` for commands that have a variable arity, which means you don't need to create lists anymore. Second, the arguments are now of type `Object` and the client is doing the proper encoding, which means users don't need to use `String` or cast to `String` everywhere...

If this was a better improvement, let's discuss on merging this.

There is a drawback, though. Given that we're using `varargs` and `Object` as type it means we can only have the `Future` based API, as we could not really differentiate from a method with a callback as last argument in terms of compiler checks.

**Comment by cescoffier** [comment]
Varargs are not very interesting, especially with `List.of` which makes list creation a no-brainer. 
Passing objects can be nice, but don't you have a cost as you need to check which type it is for every parameter. Also, key and value may use "business" types, which would require a codec. 

In my POC, I have a CodecRegistry, and an argument list builder which encodes to string the various items passed to the commands. It's not perfect as you also need to verify the "oneOf" constraint from Redis (and the few exceptions...).

**Comment by cescoffier** [comment]
See #26268

**Comment by geoand** [comment]
@cescoffier with the new Redis API in, is there anything left on this issue or can it be closed?

**Comment by cescoffier** [comment]
@geoand yes... the 3 unchecked boxes :-(

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by cescoffier** [comment]
Alright, I think it's time to close that epic once the #29615  is merged. The rest of the issues will be handled individually.

The goal was to improve the Redis experience in 2022. I think we did. We have a new client API, pub/sub support, Redis stack support, imperative/reactive, and transaction support.

**Comment by geoand** [comment]
+1 for closing

**Comment by machi1990** [comment]
+1 as well.

**Comment by cescoffier** [comment]
And DONE! So happy to have finally completed this work!

**Comment by geoand** [comment]
❤️

**Comment by geoand** [comment]
@cescoffier I was thinking, do we want to add ServiceBinding support to Redis?

**Comment by cescoffier** [comment]
The question is: is there a service binding operator out there that supports Redis and what kind of convention they use? If yes, and if the convention makes sense (can be adopted by other service binding operator implementation), then: yes.

**Comment by cescoffier** [comment]
@cmoulliard Thanks! I should be able to build the Redis connection string partially (`redis://host:port/....`) from the SBO. However, is there a Redis equivalent of `servicebinding.io/mysql` ?

**Comment by cmoulliard** [comment]
> However, is there a Redis equivalent of `servicebinding.io/mysql` ?

The Service Binding Spec mentions the property `servicebinding.io/{type}` - see [here](https://github.com/servicebinding/spec#provisioned-service) but this is up to the kubernetes operator implementing the spec to deal with that field or not. AFAIK, our red hat SBO declares it https://github.com/redhat-developer/service-binding-operator/blob/master/apis/spec/v1beta1/servicebinding_types.go#L73 but don't do anything else.

Question: What do you want (or expect) to do exactly with the Secret type `servicebinding.io/mysql` ?
