### ISSUE TITLE
OpenTelemetry SDK Autoconfigure

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#26444]
### Description

Provide support for OpenTelemetry SDK Autoconfigure:
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md

### Scheduled work:
We identified improvements (see comments bellow) to the initial PR https://github.com/quarkusio/quarkus/pull/26760 
Leading to this phased execution plan:

- [x] Refactor classes to align with metrics binding packages. This will reduce complexity from current processors.
 https://github.com/quarkusio/quarkus/pull/28314
- [x] Move opentelemetry-exporter-jaeger to quarkiverse.
 https://github.com/quarkiverse/quarkus-opentelemetry-exporter/pull/1
- [x] Move opentelemetry-exporter-otlp to otel project because it doesn't make sense not to have a default exporter .
 https://github.com/quarkusio/quarkus/pull/28487
 https://github.com/quarkusio/quarkus-platform/pull/647
 https://github.com/quarkusio/quarkus-platform/pull/648
 https://github.com/quarkusio/quarkus-super-heroes/pull/161
 https://github.com/quarkusio/quarkus-quickstarts/pull/1191
 Wiki release notes (TBD)
 Update links for published docs on the quarkiverse extension (TBD)
- [x] Move OTel SDK to runtime and fix dev mode reload.
 https://github.com/quarkusio/quarkus/pull/28792
- [x] Replace with new configs and new autoconfigutation from OTel + documentation.
 https://github.com/quarkusio/quarkus/pull/30033

Required by:
- https://github.com/quarkusio/quarkus/discussions/26438
- https://github.com/quarkusio/quarkus/issues/21535
- https://github.com/quarkusio/quarkus/pull/26367

**Comment by brunobat** [comment]
The existing WIP This PR tried to allign as best as possible the current OTel extension and the OTel side autoconfiguration. However, the PR https://github.com/quarkusio/quarkus/pull/26760 will be closed and incremental PRs will be done because:
- PR is already to big and difficult to review
- We learned that the resulting configuration objects are confusing. There is no clear separation from build and runtime configs. 
- This doesn't solve the current dev mode auto-reload problem, which will require build and configuration changes.
Pieces of the PR will be implemented in PRs with the following plan:

- [ ] Refactor classes to align with metrics binding packages. This will reduce complexity from current processors
- [ ] Move opentelemetry-exporter-jaeger to quarkiverse
- [ ] Move opentelemetry-exporter-otlp to otel project because it doesn't make sense not to have a default exporter 
- [ ] Move OTel SDK to runtime and fix dev mode reload
- [ ] Replace with new configs and new autoconfigutation from OTel + documentation
