### ISSUE TITLE
Transition to Java Flow APIs

### ISSUE THREAD

**Issue by jponge** [quarkusio/quarkus#26675]
Following the announcement that [Mutiny switches from the legacy Reactive Streams APIs to Java Flow](https://github.com/smallrye/smallrye-mutiny/discussions/986), Quarkus will need to be migrated.

- [x] Switch Mutiny to Java Flow https://github.com/smallrye/smallrye-mutiny/issues/987
- [x] Switch the Mutiny Vert.x bindings to Flow https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/573
- [x] Check the impact on Hibernate Reactive (works just fine, see https://github.com/jponge/hibernate-reactive/tree/scratchpad/mutiny-2-with-flow)
- [x] Add `Flow` types to https://github.com/smallrye/smallrye-reactive-converters https://github.com/smallrye/smallrye-reactive-converters/pull/25
- [x] Mutiny Zero projects https://github.com/smallrye/smallrye-mutiny-zero/pull/80
- [x] Check in Qute (no need to update anything)
- [x] Switch in Resteasy Reactive (migration to Flow + support of legacy RS APIs in https://github.com/jponge/quarkus/commit/e704575e2f0532778d7e40bc22597d0a7059fffb)
- [x] Switch in Reactive Messaging 
  - [x] Migration to flow draft https://github.com/smallrye/smallrye-reactive-messaging/pull/1826 (but requires other dependency alignments, Java 11 bump, compiles but does not pass tests)
  - [x] Do not migrate to Flow yet and adapt draft https://github.com/smallrye/smallrye-reactive-messaging/pull/1835 (compiles but does not pass tests yet, requires Java 11 bump)
- [x] Switch the Quarkus usage of Reactive Streams types to Java Flow
  - [x] Work in progress at https://github.com/jponge/quarkus/tree/scratchpad/rs-publisher-to-flow
- [x] Explore raising warnings with the usage of RS types in code bases from the Mutiny extension (see https://github.com/jponge/quarkus/tree/scratchpad/report-legacy-rs-publisher)

New releases aligned with `Flow`:

- [x] `smallrye/smallrye-mutiny` (testing with a `2.0.0-milestone1` release)
- [x] `smallrye/smallrye-reactive-converters` (testing with a `3.0.0-milestone1` release)
- [x] `smallrye/smallrye-mutiny-vertx-bindings` (testing with a `3.0.0-milestone1` release)
- [x] `hibernate/hibernate-reactive` (but is free of RS-dependencies, so the upgrade is trivial)
- [x] `smallrye/smallrye-reactive-messaging`
- [x] `smallrye/smallrye-mutiny-zero` (no issue here)

**Comment by cescoffier** [comment]
Marking reactive messaging as done. 

Last stop: hibernate reactive.
