### ISSUE TITLE
[EPIC] Allow to migrate from Quarkus 2 to 3 with our tooling

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#29000]
### Description

Our tooling (Maven, Gradle, CLI) should allow to migrate a project from Quarkus 2 to 3. For this we are going to use openrewrite to do the grunt work.

- [x] (WIP) List everything that should be migrated and find what currently is covered by the existing open-rewrite recipes https://hackmd.io/@ZJbzQRBpQ9OZjrz_J-KZhA/r1la7TkBo
- [x] Test recipes on quickstarts
- [x] Have a way to migrate from Quarkus 2 to 3 using a JBang script (https://quarkus.io/blog/road-to-quarkus-3/#upgrading-to-quarkus-3)
- [x] Make the `update` CLI command able to change the project (just version update or rewrite if 2 to 3)

**Comment by ia3andy** [comment]
cc @maxandersen
