### ISSUE TITLE
MicroProfile 6.0

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#31084]
Specifications:

- [x] Config 3.0.2 - same as MP 5.0
- [x] JWT 2.1 - new version - https://github.com/quarkusio/quarkus/pull/30897 & https://github.com/quarkusio/quarkus/pull/30775
- [x] Fault Tolerance 4.0.2 - same as MP 5.0
- [x] Health 4.0.1 - same as MP 5.0
- [x] OpenAPI 3.1 - new version - https://github.com/quarkusio/quarkus/pull/30883 & https://github.com/quarkusio/quarkus/pull/29815
- [x] REST Client 3.0.1 - same as MP 5.0
- [x] ~~OpenTracing - **removed**~~
- [x] ~~Metrics 5.0.0 - new version - not supported~~
- [x] OpenTelemetry Tracing 1.0 - **new specification** - https://github.com/quarkusio/quarkus/pull/31081

**Comment by radcortez** [comment]
We already communicated our plans regarding OpenTracing and Metrics here:
https://quarkus.io/blog/quarkus-observability-roadmap-2023/

We can keep the old version of MP Metrics as long as it doesn't break anything.

For OpenTracing, we have the extension marked as deprecated since 30/09. We can wait a few more months to give a six-month notice period before complete removal.

**Comment by radcortez** [comment]
@MikeEdgar, any plans on when to update Quarkus with SmallRye OpenAPI?

**Comment by MikeEdgar** [comment]
@radcortez , the 3.1 spec PR [1] was merged a few days ago and the bump for SR OpenAPI to 3.1.1 [2] includes support for the 3.1 spec :+1: 

[1] https://github.com/quarkusio/quarkus/pull/30883
[2] https://github.com/quarkusio/quarkus/pull/29815

**Comment by radcortez** [comment]
Ah, great! Sorry!

I was checking here:
https://github.com/quarkusio/quarkus/blob/main/tcks/microprofile-openapi/pom.xml#L17

And the TCK is still pointing to 3.0. No worries, I'll fix it.

**Comment by sberyozkin** [comment]
For MP JWT it is also #30775

**Comment by radcortez** [comment]
Thanks @sberyozkin !

**Comment by radcortez** [comment]
Yes, I think we are good.

The only remaining task is to remove the OpenTracing Extension (is not part of the platform anymore), and we deprecated it on 30/09/2022. Are we ok to do it? Or do you prefer to wait a little longer?

**Comment by gsmet** [comment]
If it's still working, I would wait a little longer. But announce in the 3.0 announcement that it will be gone soon.

**Comment by radcortez** [comment]
Sure. I'll close this for now, and we remove OpenTracing in the future.
