### ISSUE TITLE
New Dev UI

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#31315]
Also see https://youtu.be/EFQRSlAiz3k

### Description
These are the known outstanding items for the new Dev UI.

There is still a lot of outstanding work, thus for now the old dev ui is still available. Once all extensions and features is ported the old code can be deleted. 

You can see the new way of taking part in the Dev UI here (in progress):  https://youtube.com/playlist?list=PLLEUmLgWP9osVhex2HeEovY3a2bJUPbSV

You can also include this dummy extension:

https://github.com/phillip-kruger/quarkus-jokes

```
<dependency>
        <groupId>io.quarkiverse.jokes</groupId>
        <artifactId>quarkus-jokes</artifactId>
        <version>1.0.0-SNAPSHOT</version>
</dependency
```

Any example application that includes above, for instance: https://github.com/phillip-kruger/devui-example will show the jokes extension:

You can access the new ui under [/q/dev-ui](http://localhost:8080/q/dev-ui) (note the -ui)

![example](https://user-images.githubusercontent.com/6836179/219549259-819171a4-6070-48c8-8ef7-3517a9dd54a4.gif)

**Core functionality to be migrated:**

- [x] Extensions page
- [x] Configuration page #31553 
- [x] Continuous testing page
- [X] DevServices page - #31453
- [x] Build steps page

**Core Extensions to be migrated:**

- [x] arc
- [x] cache - #31424 
- [x] container-image - #31435
- [X] datasource - #31427 
- [X] flyway - Clement has the code
- [x] #31366
- [x] #31367 
- [x] kubernetes/vanilla
- [x] liquibase - @melloware working on it
- [X] micrometer - #31426 
- [X] qute - Martin created https://github.com/quarkusio/quarkus/pull/32063
- [x] resteasy-reactive/quarkus-resteasy-reactive - #31458
- [x] scheduler
- [x] smallrye-fault-tolerance - #31902
- [x] smallrye-graphql
- [x] smallrye-health - #31425 
- [x] smallrye-metrics
- [x] smallrye-openapi
- [x] smallrye-reactive-messaging-rabbitmq
- [x] smallrye-reactive-messaging - #31432
- [x] kubernetes/openshift
- [ ] grpc -#32592
- [ ] infinispan-client -#32593
- [ ] kafka-client - #32594
- [ ] kafka-streams - #32595
- [ ] oidc - #32031
- [ ] resteasy-reactive/rest-client-reactive - #32596
- [ ] ... more ?

**Quarkiverse extensions to be migrated:**

- [ ] quarkus-operator-sdk - https://github.com/quarkiverse/quarkus-operator-sdk/issues/557
- [ ] quarkus-neo4j - https://github.com/quarkiverse/quarkus-neo4j/issues/156
- [ ] quarkus-jpastreamer - https://github.com/quarkiverse/quarkus-jpastreamer/issues/46
- [ ] quarkus-jef - https://github.com/quarkiverse/quarkus-jef/issues/54
- [ ] quarkus-cxf - https://github.com/quarkiverse/quarkus-cxf/issues/814
- [ ] quarkus-minio - https://github.com/quarkiverse/quarkus-minio/issues/208
- [ ] quarkus-dashbuilder - https://github.com/quarkiverse/quarkus-dashbuilder/issues/18
- [ ] quarkus-ngrok - https://github.com/quarkiverse/quarkus-ngrok/issues/56
- [ ] quarkus-logging-manager - https://github.com/quarkiverse/quarkus-logging-manager/issues/187
- [ ] ... more ?

**Other things to do:**

- [x] Remove Jackson databind and use  Vertx Json (Jackson core)
- [x] Make the Menu section more accessible for extensions.
- [x] Make the bottom drawer more accessible for extensions.
- [x] Add history to server log
- [x] Investigate if dev-ui can be moved to it's own extension (out of vertx-http)
- [x] Add notification controller
- [x] Dynamic card options (web component cards)
- [x] Add importmap support for older browsers
- [x] JsonRPC should be able to return Uni - #31743
- [x] Get notification on a hot reload so we can update screen
- [x] Move the new dev UI under /dev/q and add a link to the old one
- [ ] #32597
- [ ] #32598
- [ ] #32599
- [ ] #32600

More details about the new dev UI: https://github.com/quarkusio/quarkus/wiki/Dev-UI-v2

**Comment by yrodiere** [comment]
Thanks for all the docs! I will take care of the Hibernate extensions.

**Comment by ingmarfjolla** [comment]
hi, what's the best way to pick up one of these to try and migrate?

**Comment by cescoffier** [comment]
@ingmarfjolla the easiest is to pick one extension and try to migrate it. You can find lots of details on https://github.com/quarkusio/quarkus/wiki/Dev-UI-v2.

**Comment by ingmarfjolla** [comment]
cool, i'd like to try the grpc extension if no one is working on that at the moment

**Comment by gsmet** [comment]
@phillip-kruger I will work on a preliminary version of the build steps page.

**Comment by melloware** [comment]
@phillip-kruger assign me to Liquibase I will try and tackle that one as I am a huge LB fan. 😄

**Comment by gsmet** [comment]
@melloware done!

**Comment by melloware** [comment]
You can mark Liquibase and SmallRye Metrics as done.

**Comment by geoand** [comment]
I think we should probably close this more general issue and open specific issues if and when needed

**Comment by phillip-kruger** [comment]
Closing here, as we now have individual issues for all outstanding items
