### ISSUE TITLE
Improve and fix profile configuration user experience

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3150]
With profile configurations out the door, we started to get feedback. Now is the time for a rev of fixes and improvements.

- [x] Rename quarkus-profile to quarkus.profile https://github.com/quarkusio/quarkus/issues/3145
- [x] Support Maven and Gradle properties as a build-time config source https://github.com/quarkusio/quarkus/issues/3012

- [x] Building with custom profile should run tests with the test profile by default https://github.com/quarkusio/quarkus/issues/3149
- [x] The profile a runner or native image is built from should be the default profile used unless overridden at runtime by quarkus.profile https://github.com/quarkusio/quarkus/issues/3147
- [X] Document that running the test suite under a custom test profile is done via Maven and Gradle https://github.com/quarkusio/quarkus/issues/3146
- [x] Native executable tests should be run under the test profile https://github.com/quarkusio/quarkus/issues/3148

Background info https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/NFpDtpRVZ7Y/3G7WmRMJDAAJ

**Comment by gsmet** [comment]
I will coordinate this effort.

**Comment by gsmet** [comment]
@machi1990 @gwenneg if you're looking for issues to fix, this list is a nice source. We would like to target the next release for these improvements.

Some will be simple. Some not so much so it you're interested in one, write a comment in the issue and we can discuss it.

**Comment by gwenneg** [comment]
@gsmet I haven't done a lot of tests with native images, it seems to be a good time to start diving into this topic! I may start with an easy one though since I'm already working on a few other issues.
