### ISSUE TITLE
Test builder images on various environment

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#33290]
### Description
Recently,m we had multiple issues when building native executables using the builder images (so without using a locally-installed GraalVM). Typically, the container may not have access to the host file system. 

When building a native executable using these builder images, a volume is mounted (generally `target`), so the compiler has access to the files it needs to compile, and write the produced executable. For these reasons, the compiler must have read and write access to the mounted volume.

The builder image defines a `user` to avoid running as `root`. This user has the id 1001. The files created by the container belong to that user, which obviously does not work, as the host user is rarely 1001. Thus, when launching the container, we pass a `--user` parameter overriding the last `user` from the container. This user should be the user from the local host so the graalvm compiler can read the files but also write the outcome permissions allowing the host user to access the file.

This epic is about a test campaign to be sure Quarkus supports OOTB the most _pupluar_ container environments and variants:

- [ ] Rootful Docker on Linux
- [ ] Rootless Docker on Linux
- [ ] Docker for Mac
- [ ] Docker for Windows
- [ ] Rootful Podman on Linux
- [ ] Rootless Podman on Linux
- [ ] Rootful Podman on Mac
- [ ] Rootless Podman on Mac
- [ ] Rootful Podman on Windows
- [ ] Rootless Podman on Windows

The test is fairly simple. It just needs to run a native compilation using, for example, the getting started Quarkus application. 

## Expected outcome

- We may need to tweak the discovery of some of these environments and pass the right `--user` value

**Comment by maxandersen** [comment]
I started mostly for fun a test jbang script to run various tests. code at https://github.com/maxandersen/quarkus-containertests. 

it creates a set of projects via codestarts and as such can be used to test across multiple versions fairly easy.

Might want to make these unit tests as easier to "fit in"

**Comment by cescoffier** [comment]
@maxandersen nice. I was actually thinking if we should not only use the "getting-started" but also an application using a dev service so, we can check if they are working or not and make sure we document what's required to make them work.
