### ISSUE TITLE
Improve the logic to generate TLS-based container ports by the Quarkus Kubernetes extension

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#33307]
### Description

At the moment, the Quarkus application uses some runtime properties to configure the TLS configuration. For example:

- `quarkus.http.ssl.*` to configure the HTTP TLS server
- `quarkus.management.ssl.*` to configure the Management TLS server

The problem is that some of the above properties need to be known at build time by the Quarkus Kubernetes extension to properly generate/bind the HTTPS/management ports. 

### Tasks

- [x] For the HTTP TLS configuration, add a new property `quarkus.kubernetes.ports.https.tls=true` with default value false. If users set it to true, then the container port HTTPS will be bound to the application container and to the service resource. If false, we will check whether the `quarkus.http.ssl.*` runtime properties were set at build time using the `ConfigProvider` API, and bind the container HTTPS accordingly. https://github.com/quarkusio/quarkus/pull/33696
- [x] For the Management TLS configuration, we will do the same as above but with the property `quarkus.kubernetes.ports.management.tls=true`. https://github.com/quarkusio/quarkus/pull/32902
- [x] The Quarkus Kubernetes extension will print some INFO logs saying that some runtime properties were used and can't change when running the application. For example: `quarkus.http.port`. https://github.com/quarkusio/quarkus/pull/33789
- [x] The Management port should never be bound into the generated Service resource: https://github.com/quarkusio/quarkus/pull/33694

**Comment by Sgitario** [comment]
cc @cescoffier

**Comment by Sgitario** [comment]
Closing epic since all the sub-tasks were completed
