### ISSUE TITLE
Removal of the old Dev UI

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34206]
### Description

Migrate the missing extensions and remove the old dev-ui

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

**Core Dev UI to be cleaned:**
- [x] Extensions #35317
- [x] Configuration #35163
- [x] Dev Services #35155
- [x] Continuous Testing #35154
- [x] Log streaming  #35164
- [x] Build Info #35153

**Core Extensions to be cleaned:**

- [x] arc #34971
- [x] cache #34972
- [x] container-image #34973
- [x] datasource #34974 
- [x] flyway #35073
- [x] hibernate-orm #35001
- [x] hibernate-orm-elastic #35002
- [x] kubernetes/vanilla #34983
- [x] liquibase #34984
- [x] micrometer #34982
- [x] qute #34981
- [x] resteasy-reactive/quarkus-resteasy-reactive #35046
- [x] scheduler #34980
- [x] smallrye-fault-tolerance #34979
- [x] smallrye-graphql #34976
- [x] smallrye-health #34977
- [x] smallrye-metrics #34978
- [x] smallrye-openapi #34975
- [x] smallrye-reactive-messaging-rabbitmq #35016
- [x] smallrye-reactive-messaging #35021
- [x] kubernetes/openshift #35000
- [x] resteasy-reactive/rest-client-reactive #35047
- [x] infinispan-client #35024
- [x] oidc #35048
- [x] grpc #35049
- [x] kafka-client #35050
- [ ] kafka-streams

**Quarkiverse extensions to be cleaned:**

- [x] quarkus-neo4j https://github.com/quarkiverse/quarkus-neo4j/pull/189
- [x] quarkus-operator-sdk https://github.com/quarkiverse/quarkus-operator-sdk/pull/559
- [x] quarkus-dashbuilder https://github.com/quarkiverse/quarkus-dashbuilder/pull/58
- [x] quarkus-jpastreamer https://github.com/quarkiverse/quarkus-jpastreamer/pull/81
- [x] quarkus-minio https://github.com/quarkiverse/quarkus-minio/pull/252
- [x] quarkus-ngrok https://github.com/quarkiverse/quarkus-ngrok/pull/74
- [ ] quarkus-jef 
- [ ] quarkus-cxf
- [ ] quarkus-logging-manager

**Comment by phillip-kruger** [comment]
For completing the migration to the new UI, 
this is the list I have so far (from #31315 ):

- [ ] grpc - #32592
- [ ] kafka-client - #32594
- [ ] kafka-streams - #32595
- [ ] quarkus-jef - https://github.com/quarkiverse/quarkus-jef/issues/54
- [ ] quarkus-cxf - https://github.com/quarkiverse/quarkus-cxf/issues/814
- [ ] quarkus-logging-manager - https://github.com/quarkiverse/quarkus-logging-manager/issues/187

Whether or not we can remove the old Dev UI without the above I am not sure, I assumed that needs to move first.

I also still have on my list:

- [ ] Arc bean relations graph as in the old Dev UI
- [ ] Build info execution graph as in the old Dev UI

There might also be some more tests that needs to be implemented for the new Dev UI

- [ ] ...
