### ISSUE TITLE
Renaming reactive messaging to Quarkus messaging

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#39279]
Following the _big rename_ and avoiding user confusion around the "reactive" word, we want to rename "reactive messaging" into "quarkus-messaging". The implementation would not change; it would just be the user-facing name. 

- `quarkus-smallrye-reactive-messaging` =>  `quarkus-messaging`
- `quarkus-smallrye-reactive-messaging-kafka` =>  `quarkus-messaging-kafka`
- `quarkus-smallrye-reactive-messaging-amqp` =>  `quarkus-messaging-amqp`
- `quarkus-smallrye-reactive-messaging-mqtt` =>  `quarkus-messaging-mqtt`
- `quarkus-smallrye-reactive-messaging-pulsar` =>  `quarkus-messaging-pulsar`
- `quarkus-smallrye-reactive-messaging-rabbitmq` =>  `quarkus-messaging-rabbitmq`

Relocations will be configured to prevent user disruption. Thus, applications using the previous artifactIds will still work.

## Tasks

- [ ] Renaming `quarkus-smallrye-reactive-messaging` to  `quarkus-messaging` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-kafka` to  `quarkus-messaging-kafka` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-amqp` to  `quarkus-messaging-amqp` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-mqtt` to  `quarkus-messaging-mqtt` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-pulsar` to  `quarkus-messaging-pulsar` and setting up relocation
- [ ] Renaming `quarkus-smallrye-reactive-messaging-rabbitmq` to  `quarkus-messaging-rabbitmq` and setting up relocation
- [ ] Update all documentation (getting started, and reference guides)
- [ ] Updating reactive and virtual thread documentation (the extensions are likely mentioned) 
- [ ] Relocating configuration using `quarkus.reactive-messaging` or `quarkus.reactive.messaging` to `quarkus.messaging`

**Comment by gsmet** [comment]
This is handled here: https://github.com/quarkusio/quarkus/pull/39301 .

Quickstarts PR will come soon.

**Comment by cescoffier** [comment]
Awesome @gsmet ! I will have a look tomorrow.
