### ISSUE TITLE
Build a static website for the project

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#417]
We need snippets of content for the following subjects. A paragraph is good unless stated otherwise.
I am aware of the potential duplicate or overlapping on subjects but this content will be used either as subset of each or by merging them to create the website content.

Put it under the docs asciidoc in a `topic` subdirectory.

## Meta subjects mandatory

- [ ] Categories https://github.com/jbossas/protean-shamrock/issues/994

## Snippets mandatory

- [ ] Quarkus vision https://github.com/jbossas/protean-shamrock/issues/1003
- [ ] View on standards https://github.com/jbossas/protean-shamrock/issues/995
- [x] Target audience and continuum of usage https://github.com/jbossas/protean-shamrock/issues/996
- [ ] What is GraalVM https://github.com/jbossas/protean-shamrock/issues/997
- [ ] Code for home page https://github.com/jbossas/protean-shamrock/issues/998 
- [ ] Why are we Graal VM optimised https://github.com/jbossas/protean-shamrock/issues/999
- [ ] Why are we optimized for container first https://github.com/jbossas/protean-shamrock/issues/1000
- [x] Developer joy https://github.com/jbossas/protean-shamrock/issues/1001
- [ ] Why hot reload is awesome https://github.com/jbossas/protean-shamrock/issues/1002
- [ ] Extension ecosystem https://github.com/jbossas/protean-shamrock/issues/1004
- [x] Community page https://github.com/jbossas/protean-shamrock/issues/1005
- [ ] FAQ on Quarkus https://github.com/jbossas/protean-shamrock/issues/1006
- [ ] Page on Quarkus architecture readable by humans and not knowing SubstrateVM https://github.com/jbossas/protean-shamrock/issues/1007
- [x] Serverless https://github.com/jbossas/protean-shamrock/issues/1008

## Nice to have

- [ ] Thorntail landing page (full page with migration how to over time)
- [ ] Spring migration (likely a page than one paragraph)
