### ISSUE TITLE
Security Tracker for 1.0

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4369]
This is a tracker issue for all Security issues that should be part of 1.0.

*  (**deferred**) JPA Identity Provider (optional) #4347
- [x] FORM based auth support for simple applications (essential) #4348
- [x] CDI security interceptor for @RolesAllowed etc (essential) #4334
- [x] Unified HTTP permissions layer (essential) #4349
- [x] HashiCorp Vault: #2764 (mostly done)
- [x] Elytron JDBC IdentityProvider: #3586 (mostly done)
- [x] [OIDC enhancements](https://github.com/quarkusio/quarkus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22component%3Aoidc%22) - (To be assigned to Pedroigor)

**Comment by rsvoboda** [comment]
Sorry, miss-click :(

**Comment by stuartwdouglas** [comment]
yes, although exactly what is required for OIDC is still up in the air. I don't think all the OIDC enhancements will make it for 1.0

**Comment by paulrobinson** [comment]
@stuartwdouglas Can you add assignees to these issues please?

#4347 Add a JPA Identity Extension
#2764 Support distributed configuration with HashiCorp Vault
#3586 Enhance Elytron Security extension to support a database as identity store

**Comment by paulrobinson** [comment]
@stuartwdouglas Is this Epic complete now? Can you move to 'Review' state if it needs any final review, or 'done' if it's totally finished. 

We're using the Epic board to track this: https://github.com/orgs/quarkusio/projects/5

**Comment by paulrobinson** [comment]
@stuartwdouglas is this all done for 1.0.0.Final now?
