### ISSUE TITLE
Platform & Tools MVP

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#4566]
@maxandersen this needs cleanup moving back to the backlog

- [ ] Document quarkus-extension.properties #4361
- [x] Generation of extension.json should allow for overrides #4320
- [ ] Document what it takes to be added to the platform #4319
- [x] curate extensions in core #4316
- [x] create tooling SPI to allow platform separation #4315
- [x] Define and create platform bound extensions.json #4313
- [x] Make gradle plugin available for easy/conventional gradle usage #4311
- [x] Add Apache Camel extension available in project creation tooling #3962
- [x] Quarkus Platform Repository #3329
- [x] Setup CI job to test latest core with latest platform before release #4318
- [x] Extension metadata and generation of extensions.json #4423
- [x] Generate extensions.json based on `quarkus-extension.properties` #4317
- [x] Quarkus Platform should not ban test scope in endorsed third party test projects #3136
- [x] Add extension metadata to all the extensions #833
- [x] fix extension descriptions #4724 
- [x] Define a notion of a beta/experimental extension in the tooling #4771 
- [ ] Define the notion of the preferred extension for a label #4772 

Maybe:
- [ ] introduce parent platform pom #4723

**Comment by emmanuelbernard** [comment]
@maxandersen so looking at it, it feels like the remaining tasks are really doc, can we spawn these off and consider this one closed? (Thinking roadmap)

**Comment by maxandersen** [comment]
closing this and putting leftovers on #5962
