### ISSUE TITLE
Plans on testing strategy and approach

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#461]
We need a guide of course capturing that.
Potentially some frameworks helping.

Sub issues for first release

* [ ] Guide https://github.com/jbossas/protean-shamrock/issues/555
* [x] JUnit 5 https://github.com/jbossas/protean-shamrock/issues/553

Other sub issues

* [ ] Arquillian like subset of the app with no zipping https://github.com/jbossas/protean-shamrock/issues/554
* [x] `@Inject` in unit tests https://github.com/jbossas/protean-shamrock/issues/620
* [ ] Configuration test in Kubernetes https://github.com/jbossas/protean-shamrock/issues/557
* [ ] Mock and Bean alternatives https://github.com/jbossas/protean-shamrock/issues/568
* [x] Inject configured REST client https://github.com/jbossas/protean-shamrock/issues/569
* [ ] Reset data between tests via Hibernate ORM https://github.com/jbossas/protean-shamrock/issues/583

**Comment by hantsy** [comment]
Currently it seems all quickstarts are demonstrating  `QuarkusTest` of JAX-RS. 

Hope it includes:
* Mockito integration, mock CDI by some annotations like @MockBean @SpyBean
* Provides embedded server for test purpose, such as H2 for JPA, embedded Mongo for Mongo. etc
* Integrate TestContainers to setup dependent service(such as a MySql server) in Docker directly

**Comment by antonin-arquey** [comment]
> Wondering about things like Cucumber, or let's say "spec based testing". I don't know if it's still popular.

Hi, we use Cucumber for testing in my organization, but I can't get it to work with Quarkus tests. The quarkus context is never started even with the `@QuarkusTest` annotation. 

We use it with SpringBoot thanks to the [spring cucumber plugin](https://github.com/cucumber/cucumber-jvm/tree/master/spring) and it works great !

Would it be possible to do something similar with Quarkus ?

**Comment by stuartwdouglas** [comment]
It looks like Cucumber is still using JUnit 4, while we are using JUnit 5.
Did you try including junit-vintage-engine as the cucumber docs suggest?

It's likely that we will need to write some kind of plugin to allow it to
work, especially after the class loading changes that are coming in with my
class loading PR.

Stuart

**Comment by emmanuelbernard** [comment]
This issue is not mostly obsolete, closing.

**Comment by panchitoboy** [comment]
> 
> 
> > Wondering about things like Cucumber, or let's say "spec based testing". I don't know if it's still popular.
> 
> Hi, we use Cucumber for testing in my organization, but I can't get it to work with Quarkus tests. The quarkus context is never started even with the `@QuarkusTest` annotation.
> 
> We use it with SpringBoot thanks to the [spring cucumber plugin](https://github.com/cucumber/cucumber-jvm/tree/master/spring) and it works great !
> 
> Would it be possible to do something similar with Quarkus ?

Did you find a solution for this?

**Comment by juanmanuelz** [comment]
> > > Wondering about things like Cucumber, or let's say "spec based testing". I don't know if it's still popular.
> > 
> > 
> > Hi, we use Cucumber for testing in my organization, but I can't get it to work with Quarkus tests. The quarkus context is never started even with the `@QuarkusTest` annotation.
> > We use it with SpringBoot thanks to the [spring cucumber plugin](https://github.com/cucumber/cucumber-jvm/tree/master/spring) and it works great !
> > Would it be possible to do something similar with Quarkus ?
> 
> Did you find a solution for this?

I'm using a workaround. Using the information here https://www.objectivity.co.uk/blog/cucumber-parallel-scenarios-junit5-gradle/ and https://github.com/cucumber/cucumber-jvm/tree/master/junit-platform-engine . In addition to that, I had to create some code to mimic what happens when @QuarkusTest is used (I will write you back with the details, is nothing worth a gist or a reference here because is just a really "crappy" workaround to be used in the meantime this is sorted out properly).

**Comment by stuartwdouglas** [comment]
Do you have a simple @QuarkusTest + Cucumber example I could look at to see if I could get it to work? I have never used cucumber, so I am not really sure what the expectation is here, but I think I would need to write a custom quarkus-cucmber module to integrate them.

**Comment by msigl** [comment]
> > > > Wondering about things like Cucumber, or let's say "spec based testing". I don't know if it's still popular.
> > > 
> > > 
> > > Hi, we use Cucumber for testing in my organization, but I can't get it to work with Quarkus tests. The quarkus context is never started even with the `@QuarkusTest` annotation.
> > > We use it with SpringBoot thanks to the [spring cucumber plugin](https://github.com/cucumber/cucumber-jvm/tree/master/spring) and it works great !
> > > Would it be possible to do something similar with Quarkus ?
> > 
> > 
> > Did you find a solution for this?
> 
> I'm using a workaround. Using the information here https://www.objectivity.co.uk/blog/cucumber-parallel-scenarios-junit5-gradle/ and https://github.com/cucumber/cucumber-jvm/tree/master/junit-platform-engine . In addition to that, I had to create some code to mimic what happens when @QuarkusTest is used (I will write you back with the details, is nothing worth a gist or a reference here because is just a really "crappy" workaround to be used in the meantime this is sorted out properly).

I'm having the same issue. Could you share your solution? :-)
