### ISSUE TITLE
Create RSS test bed

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#4610]
- [x] Lab automation scripts for quarkus-quickstart building against master
- [x] Create PerfRepo metrics, tags and test defintions
- [x] Create Jenkins pipeline, scheduled to run daily
- [x] Configure regression alerts
- [x] Configure lab smtp mail service
- [x] Validate alerting

**Comment by paulrobinson** [comment]
@johnaohara Are there any outstanding issues, for the RSS testbed work, that need fixing for 1.0.0?

If not, you can mark this Epic as done :-)

Otherwise, can you list the issues in the Epic description, using the check-list markup? See here for an example Epic: #4566

**Comment by johnaohara** [comment]
I have fixed some issues with PerfRepo and updated our perf lab with a newer version, regression alerting will be enabled today

**Comment by paulrobinson** [comment]
@johnaohara will this Epic be complete when the alerting is in place?

**Comment by johnaohara** [comment]
@paulrobinson yes, I am validating that alerting is working as expected, I have update the epic with the list of actions that have been complete to date

**Comment by paulrobinson** [comment]
That's great, thanks. I've moved the Epic to 'in progress' on the planning board: https://github.com/orgs/quarkusio/projects/5 as it has a complete list of work, and is in progress.

**Comment by paulrobinson** [comment]
@johnaohara did you manage to verify that the alerting was working as expected?

**Comment by johnaohara** [comment]
@paulrobinson yes, have validated alerting, closing issue
