### ISSUE TITLE
Tidy Extensions

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#4616]
Using this document to coordinate:

https://docs.google.com/spreadsheets/d/1ngALlwB7UqTX_OxnOglo2HeFmoZkXjxJvfMwhX5LOlM/edit#gid=0

### Now:

- [x] Review the assessment criteria (items in the top row).
- [x] Review the maintainer list.

### When the above is confirmed:
- [x] Extension maintainers fill out the questionnaire for their extensions

### In parallel to the above:
- [x] Establish a simple classification system to label extensions. For example, [Alpha, Beta, GA] or [experimental, incubating, stable], etc.
- [x] Classify extensions
- [x] Find a way to associate the labels with the extension
- [x] Update code.quarkus.io to show the labels

**Comment by paulrobinson** [comment]
@maxandersen, @emmanuelbernard Is this done enough for 1.0.0.Final, or is there still more to do?

Doing a final review before we call this Epic done.

**Comment by maxandersen** [comment]
from my usecase of getting markers for what is preview and not for platform/code.quarkus.io I think we are good. 

I can't right now think of more we need to do right now. If anyhthing that would be follow up issues/epics.
