### ISSUE TITLE
Release Activities for 1.0.0.RC1

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#4617]
In addition to making the required code changes (covered by other Epics), there are several other tasks that need to be competed for the 1.0.0 release. These are as follows:

- [x] Prepare Blog post for 1.0 @jclingan @tqvarnst @emmanuelbernard 
- [x] Prepare website change for proper RSS and boot time numbers #4560 @jkbrock @johnaohara 
- [x] Prepare announcement tweet @emmanuelbernard 
- [x] Prepare email to quarkus-dev @emmanuelbernard 
- [x] Prepare updated website homepage @jkbrock @gsmet @adelasofia

**Comment by paulrobinson** [comment]
@gsmet, @cescoffier Can you help populate this list of tasks? Any other people we should ping for input?

**Comment by gsmet** [comment]
We also need a proper sexy tweet and probably an email too.

1.0 is worth having someone like @emmanuelbernard writing all of them to get some good vibes.

**Comment by Sanne** [comment]
> Proper RSS numbers in the website #4560

And update boot times?

**Comment by paulrobinson** [comment]
@Sanne added the boot times item.

**Comment by emmanuelbernard** [comment]
@johnaohara is mr boot time

**Comment by paulrobinson** [comment]
@emmanuelbernard do you know who the tasks here should be assigned to? For those that don't warrant a GitHub issue, can you tag them in the checklist item?

**Comment by emmanuelbernard** [comment]
@paulrobinson done

**Comment by paulrobinson** [comment]
@emmanuelbernard, @gsmet: Will we need to do all of these again for the 1.0.0.Final release?

**Comment by emmanuelbernard** [comment]
I’m thinking we need a blog announcing 1.0 final and focusing on the
roadmap. And the usual tweet etc.

**Comment by paulrobinson** [comment]
OK. I've cloned to #5333 as it's really a new set of tasks.
