### ISSUE TITLE
 Better Gradle support out on our quest out of beta

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5101]
**Description**

There are some corner cases while using Gradle quarkus tooling or the gradle file is not behaving well.

This issue is to collect the known "bigger" issues for info.

related: 
https://github.com/quarkusio/quarkus/pull/4905#issuecomment-546851800 
update documentation to have both maven and gradle variation

Definition of move Gradle out of beta (2020-05-20) 
Good parts:
  - we have tests
  - classloader isolated
Needed:
  - be a good gradle citizen (in/output)
  - devmode on run from ide
  - deployment/runtime mismatch (affects gradle more than maven)

## Epic items
(this section is auto-generated - manual edits will get lost)
- [x] [#3552](https://github.com/quarkusio/quarkus/issues/3552) [gradle] gradle test still not work
- [x] [#4960](https://github.com/quarkusio/quarkus/issues/4960) Building with Gradle gives a warning about CDI dependencies
- [x] [#4982](https://github.com/quarkusio/quarkus/issues/4982) Do not require Gradle to be installed to generate the Gradle wrapper
- [x] [#5204](https://github.com/quarkusio/quarkus/issues/5204) Gradle plugin does not work with plugins DSL
- [x] [#5488](https://github.com/quarkusio/quarkus/issues/5488) EntityManager in not injected when using devmode with gradle
- [x] [#5722](https://github.com/quarkusio/quarkus/issues/5722) Gradle plugin doesn't support multi module project well.
- [x] [#6035](https://github.com/quarkusio/quarkus/issues/6035) Pass Kotlin compiler plugin options to dev mode in Gradle
- [x] [#9046](https://github.com/quarkusio/quarkus/issues/9046) Improve gradle and maven test harness to give us more release confidence
- [x] [#9281](https://github.com/quarkusio/quarkus/issues/9281) Gradle build cache is not being leveraged

**Comment by gastaldi** [comment]
Here is a Gradle project using the minimum configuration (which should be generated by our tools): https://github.com/gastaldi/gradle-quarkus-project

**Comment by 4ntoine** [comment]
It would be great to have Maven/Gradle switch for configuration too

**Comment by maxandersen** [comment]
@4ntoine can you elaborate a bit on what you are looking for ?

**Comment by 4ntoine** [comment]
@maxandersen Sure, i'd like to have a switcher maven/gradle(groove/kotlin) in build configuration files, like follows (see my link):
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-bom</artifactId>
            <version>${quarkus.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<build>
    <plugins>
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
                <execution>
                    <goals>
                        <goal>build</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```
in most cases the transition is pretty straight-forward, like:
```
<dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy</artifactId>
    </dependency>
```
can be achieved with Gradle's:
```
implementation("...") // Kotlin DSL
```
However there can be more complicated usage examples.

It just removed the barriers for the newcomers (especially from Android world who mostly use Gradle as build tool).

**Comment by maxandersen** [comment]
ah you mean you don't like the use of enforced-platform/bom in our gradle file, but prefer the quarkus plugin to do the scaffolding ? 

Yes, that is something I want too - just trying to figure out how we do it best reusing the dep set from the bom's the best way.

**Comment by 4ntoine** [comment]
@maxandersen Sorry for being not clear enough. I've meant "provide configuration with Gradle everywhere where you can see configuration with Maven".

**Comment by maxandersen** [comment]
aaaaah! have our documentation include both maven and gradle snippets for needed config. Gotcha! 

And I fully agree-  I would prefer we get the actual gradle configuration simplified before go update all the docs - but yes, agreed.

**Comment by tobad357** [comment]
@maxandersen I'll chime in with that it seems quarkusBuild doesn't work well with org.gradle.caching=true and Up To Date check.

I've tested by 
* add "org.gradle.caching=true" to gradle.properties
* ./gradlew build --scan
* ./gradlew build --scan

quarkusBuild and test show as being rebuilt while by right they should be up to date as I did no changes to the project between builds

**Comment by SetoKaiba** [comment]
Hi. I'd like to know whether gradle would be with the same features that maven plugin provides. I get little support in the WildFly Swarm project before. And I contribute to it to fix some bugs as well. It's been said to be a brother project of this project. This project seems to be with less feature gradle plugin as well. So I'm curious whether the gradle plugin is just a beginning. Or it will get little focus on it? Thank you. 
I know that the Maven is more popular. But my projects are with Android clients which uses Gradle to manage. It's better to with Gradle that without publish to local maven first for some share stuffs.

**Comment by SetoKaiba** [comment]
And I made a PR for better multi project support.

**Comment by maxandersen** [comment]
@SetoKaiba goal are that they should be equivalent. Only additional task i'm aware of for maven is the "create" project but otherwise everything else should be possible with Gradle.

**Comment by lfmunoz** [comment]
https://quarkus.io/guides/gradle-tooling  documentation should mention which gradle version you are supporting. Does not work with gradle 4.6 but it did work with 5.6.4

**Comment by gastaldi** [comment]
@lfmunoz good catch. Mind providing a PR? It should be 6.2

**Comment by lfmunoz** [comment]
@gastaldi Will do this week

**Comment by emmanuelbernard** [comment]
@maxandersen and all, how much will we do in the next 3-6 months? (asking for a friend with a roadmap).

**Comment by ebramirez** [comment]
Does https://github.com/quarkusio/quarkus/issues/8950 belong here?

**Comment by mboulatian** [comment]
I just downloaded the project both ways using gradle - starter project and maven architype. Both ways don't work and I get the following message: Plugin [id: 'io.quarkus', version: '1.5.2.Final'] was not found in any of the following sources:

**Comment by oztimpower** [comment]
Hi @mboulatian Quarkus 1.5.2 was just released overnight and there is a slight lag of the binaries being available on the maven repositories. Can I suggest you try again in one day or modify the version in your maven Pom or gradle build to 1.5.1?

**Comment by mboulatian** [comment]
thanks for quick reply. I will try tomorrow.

**Comment by mboulatian** [comment]
Just for curiosity I tried changing the versions in gradle.properties and settings.gradle to 1.5.1 and still the same result. I better wait for  24 hours and if result the same I will report it here

**Comment by oztimpower** [comment]
Sorry I should have been more specific. 1.5.1.Final. 

If you check on the maven repo you’ll see what the latest version is. I did a quick check when seeing your post. 

Yes do wait another day and also do a quick check on the maven repos to see if the new version is now available. 



<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-core</artifactId>
    <version>1.5.1.Final</version>
</dependency>

**Comment by emmanuelbernard** [comment]
Hey all, Please enlist to #10189 as it is the follow up actions post 1.6.

**Comment by sebersole** [comment]
> Here is a Gradle project using the minimum configuration (which should be generated by our tools): https://github.com/gastaldi/gradle-quarkus-project

@gastaldi I tried cloning this and playing with it but it will not build for me:

```
Settings file '/home/sebersole/projects/quarkus/gradle-quarkus-project/settings.gradle' line: 2

A problem occurred evaluating settings 'gradle-quarkus-project'.
> Could not find method plugins() for arguments [settings_dnolxr5c1cg7bohgrbd8ry36q$_run_closure1$_closure2@76adbf74] on object of type org.gradle.plugin.management.internal.DefaultPluginManagementSpec.
```

You expecting that?

**Comment by gastaldi** [comment]
@sebersole that project is really old and the changes were already integrated in the quarkus core codebase. I'll delete that repository and I'd recommend you to use the Gradle project from https://code.quarkus.io/
