### ISSUE TITLE
Release Activities for 1.0.0.Final

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5333]
In addition to making the required code changes (covered by other Epics), there are several other tasks that need to be competed for the 1.0.0.Final release. These are as follows:

- [x] Prepare Blog post for 1.0 @jclingan @tqvarnst @emmanuelbernard 
- [x] Prepare announcement tweet @emmanuelbernard 
- [x] Prepare email to quarkus-dev @emmanuelbernard 
- [x] Prepare updated website homepage @jkbrock @gsmet @adelasofia
