### ISSUE TITLE
Qute MVP

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5594]
### Description
Release the first version of Qute.

### Analysis
_Links to analysis docs (E.g Design, Requirements, etc)_

### Tasks
- [x] Initial PR - includes qute-core, core quarkus integration and RESTEasy integration
- [x] Basic Guide
- [x] Reference Guide
- [x] Quickstart - https://github.com/quarkusio/quarkus-quickstarts/pull/395
- [x] Mailer extension integration
