### ISSUE TITLE
Classloader Isolation Model

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5597]
### Description
Due to the Gradle specificities and the bug around Panache entities + typed queries, we need this clarified CL model.

### Analysis
Design work has started on the public list https://groups.google.com/forum/#!topic/quarkus-dev/3u24xR6H7zs and https://docs.google.com/document/d/1XOD4_OWi93gD0mAT39fyZvDCVSwPbH3yVpkBbM1yPVg/edit?usp=sharing once everyone is happy I will start to implement it.

### Related Issues
- [ ] https://github.com/quarkusio/quarkus/issues/6190
- [ ] https://github.com/quarkusio/quarkus/issues/1724
- [ ] https://github.com/quarkusio/quarkus/issues/5354
- [ ] https://github.com/quarkusio/quarkus/issues/770
- [ ] https://github.com/quarkusio/quarkus/issues/4960
- [ ] https://github.com/quarkusio/quarkus/issues/3917

### Tasks
- [ ] _Checklist of sub tasks goes here_

**Comment by paulrobinson** [comment]
@stuartwdouglas are the related issues planed for completion as part of this Epic? Or, are they issues that we can fix once this Epic is complete? 

The reason I ask, is because GHIssues uses the checklists in the description as a measure of progress. So unfortunately, it doesn't work well if checklists are used for other things.

**Comment by stuartwdouglas** [comment]
Most of the issues will be fixed by the PR, I referenced the ones I have explicitly tested. Once this PR goes in though the epic is done, and anything else that needs to happen is just a normal bug.

**Comment by paulrobinson** [comment]
Great, thanks.
