### ISSUE TITLE
Expose mini extension APIs for applications

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5601]
### Description
Allow applications write build-time operations or resource enlistment for GraalVM without having to use the nasty command line arguments or write a full extension.

### Analysis
_Links to analysis docs (E.g Design, Requirements, etc)_

### Tasks
- [ ] Support for reflective hierarchies
- [ ] Support for Runtime Initialised classes
- [ ] Support for Runtime Reinitialised classes
- [ ] Support for Service providers
- [ ] Support for defining JDK proxy classes
- [ ] Support for including resource bundles
- [ ] Better application resource handling

**Comment by n1hility** [comment]
retiring issue
