### ISSUE TITLE
Command Line Mode support (initial)

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5656]
### Description
Having the ability to launch Quarkus as a short live, command line application. For example with Aesh or Picocli (the later is already GraalVM compatible and very popular)

### Analysis
Discussion currently happening on the mailing list:
* [Thoughts on Command Mode](https://groups.google.com/forum/#!msg/quarkus-dev/hxSVglF-zhA/6uCIUgafBAAJ)
* [Command Mode](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/KiqCbqQZe_o/DEVowWmyAQAJ)
* [Application startup redesign for command-based apps](https://groups.google.com/forum/#!topic/quarkus-dev/d39bd4gMb8I)

### Tasks
- [ ] Introduce command line argument based configuration binding (#6497)
- [x] Introduce and use exit request API with wait-for-exit method (#6498)
- [ ] Introduce ability to recognize and execute user main method(s) (with optional command line arguments, optionally returning an exit code) by annotation (#6499)

**Comment by stalep** [comment]
Just a FYI, Æsh is GraalVM compatible as well (had it earlier than picocli :)
- not a popular as I have not had time to work on docs/webpage much and push it to projects, but AFAIK there are no features picocli has that's not in Æsh. - and Æsh have command mode with support for custom CommandInvocations so that it's very easy to add Quarkus specific capability when invoking the commands. Eg: look at Georgios POC for the first CLI attempt.

**Comment by maxandersen** [comment]
> * Eg: look at Georgios POC for the first CLI attempt

where is that ? link ?

**Comment by bric3** [comment]
@maxandersen I think that's a typo, and @stalep refers to this PR : https://github.com/quarkusio/quarkus/pull/1301/files

**Comment by remkop** [comment]
Question about #6497 (configuring Quarkus from command line args): this is now listed as the first task in this epic, but is this a showstopper?

The Quarkus user community is very eager to get their hands on this Command Line Mode feature (and have been for [over a year](https://github.com/quarkusio/quarkus/issues/284)). Would it not make sense to focus on the minimum credible deliverable initially, and add features like #6497 later?

**Comment by maxandersen** [comment]
Yes @remkop, we just went through and triaged the work for this and a bunch of others. Don't get stuck on the sequence of bullet items in the epics. The important part is that we got agreement on how #6498 and #6499 will work. We are many eagerly waiting on this - have a little more patience :)

**Comment by remkop** [comment]
@maxandersen Understood, and thanks for providing insight into the process!

**Comment by lburgazzoli** [comment]
We need this also in camel-k to support delegating scheduling to the platform (k8s)

**Comment by remkop** [comment]
Quarkus team, would it be possible to provide a regular status update? From the outside it looks like there is nothing happening...

**Comment by maxandersen** [comment]
PR #7681 is on its way.

**Comment by maxandersen** [comment]
@remkop et.al. then fyi #7681 is. now working and looking for feedback/comments if you are interested in trying it out. Has docs and all included.
