### ISSUE TITLE
Misc Hibernate & Persistence improvements for 1.1

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5706]
### Description

Various tasks related to improving Hibernate for 1.1

### Analysis

(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks

- [ ] Multiple datasource support
- [ ] Resolve Jackson limitations https://github.com/quarkusio/quarkus/issues/4644
- [ ] Document multi-dialect needs and how to address them
- [ ] Fix time zone support
- [ ] default cache mode
- [ ] disable 2nd level cache via property
- [ ] Agroal: Support pre-acquire listeners and self registration https://github.com/quarkusio/quarkus/issues/5381
- [ ] Agroal: Unwrap the Datasource from the Arc Proxies
- [ ] Reconfigure ORM for less aggressive connection release strategies
- [ ] Implement type-safe query https://github.com/quarkusio/quarkus/issues/5637
- [ ] Byte Buddy (and possibly others) are augmentation-only requirements but currently needs to be listed as a runtime dependency to workaround classolading limitations - might be resolved soon by the classloader re-design?
- [ ] Review the documented limitations, some could be removed.

@Sanne can you link to the relevant issues ? And prioritize them. Thanks! We won't do all most likely

**Comment by paulrobinson** [comment]
@emmanuelbernard it sounds like @Sanne is the lead for this Epic, is that right?

**Comment by emmanuelbernard** [comment]
yes

**Comment by Sanne** [comment]
Closing as this is out of date - and out of sync with further evolutions.
