### ISSUE TITLE
Mutiny a.k.a Uni / Multi

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5707]
### Description

Deliver enough of the new reactive type strategy

### Context
Uni/Multi (also named Mutiny) is a new reactive programming API that has been designed around a more fluent API. 
Uni/Multi provides 2 types:
* Uni for stream with 0..1 items. Uni does not implement Reactive Streams, but follow a subscription approach
* Multi for stream with 0..n items. Multi implement Reactive Streams back-pressure protocol.

Uni/Multi innovates on 2 main aspects:
* The API provides more guidance to the user, trying to avoid the 400 methods / class issues as well as the multi-overloading of some method (flatMap has around 16 variants)
* The API also gives the possibility to convert from/to other reactive programming library and model such as Reactor, RX Java, CompletionStage

Current repo: https://github.com/smallrye/smallrye-uni-multi

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
Deliver an early version of Uni/Multi - Clement is kinda working on it
- [x] Implement a new reactive programming library providing enough operator to replace RX Java 2
- [x] Add support for MP Context propagation
- [x] Rewrite the Multi support to avoid bringing RX Java to the classpath
- [x] Write documentation
    * [x] Write rationale
    * [x] Write use-case based documentation
    * [x] Write "how to navigate in the API"

Migrate Reactive APis to Uni/Multi (Axle generation)
- [x] Extend the Axle code generator to generate Vert.x-based client using the Uni/Multi type
Current code: https://github.com/smallrye/smallrye-reactive-utils/tree/master/vertx-axle-clients
- [x] All the reactive api from quarkus need to be migrated to the uni/multi model (or rather offer Uni / Multi as option)
    - Each module -> A task (This includes Mongo, Mailer, Neo4J...)
- [x] RestEasy uni/multi support
    - Need to extend resteasy to support the uni and multi types

**Comment by emmanuelbernard** [comment]
CC @cescoffier

**Comment by paulrobinson** [comment]
@emmanuelbernard is it @cescoffier that we need to lead this Epic?

**Comment by emmanuelbernard** [comment]
yes

**Comment by cescoffier** [comment]
The integration of mutiny in Quarkus has started, see #6416, it's definitely WIP and lots of work is still required.

**Comment by cescoffier** [comment]
Integration is covered by #7097.
