### ISSUE TITLE
Push forward reactive messaging needs

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5709]
### Description

Quarkus interest in the Reactive Messaging improvements

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks

- [x] JMS support
    - Implement, test and integrate a JMS connector for reactive messaging
    - Integrate into quarkus with Artemis connection factory
- [x] Integration with context propagation
    - Give the possibility to propagate the context in a reactive messaging pipeline 
    - Allow message processor to extend, retrieve and update the context
    This task may require the implementation of another _context handler_.
- [x] Improved emitter support
    - Allow the emitter to be notified when the sent message is acknowledged
    This is likely a breaking change.
- [x] In-Memory connector
    - Give an easier way to test event-driven applications by mocking the external brokers
    - Integration in Quarkus
- [x] Better Kafka (Avro, JsonB, codecs, multi-consumer…)
    - Provide Avro support to the kafka connector
      - Integrate avro in the build steps + hot reload
      - Generate the Avro class
      - Manage schema registration and retrieval
      - Add reflection build items
     - It requires a base Avro extension / annotation processor (to be investigated)  handling the code generation
    - Same as for Avro with Protobuff
    - Same as for Avro with JsonB
    - Multi-consumer: 
        - Increase the concurrency when using kafka to consume several partitions at the same time
    - Converter support https://github.com/smallrye/smallrye-reactive-messaging/issues/331
    - Multi-consumer
        - Increase the concurrency when using kafka to consume several partitions at the same time
        - https://github.com/smallrye/smallrye-reactive-messaging/issues/329
        - Upstream issue: https://github.com/smallrye/smallrye-reactive-messaging/issues/328
- [x] New fault-tolerance model
    - Define a new model for reactive fault tolerance
    - Dead mailbox, retry, ack timeout, continue, avoid upstream cancellation...
- [x] RabbitMQ support
    - Implement a RabbitMQ connector for reactive messaging
    - Need interested community contribution
    - Upstream issue: https://github.com/smallrye/smallrye-reactive-messaging/issues/330
- [x] Add support for `@Blocking`
     - Allow the user to indicate that a processing is blocking and so need to be off-loaded to another thread.
     - Upstream issue: https://github.com/smallrye/smallrye-reactive-messaging/issues/79
- [x] Web Socket connector
     - Implement a connector allowing to receive messages from a web socket and sending messages to a web socket (broadcast)
     - The message is built from the payload 
     - https://github.com/smallrye/smallrye-reactive-messaging/issues/332
- [x] Multi-channel incoming
     - Allow merging channels on a method
     - https://github.com/smallrye/smallrye-reactive-messaging/issues/333
- [x] Allow observing acknowledgement
     - Allow listening for message acknowledgement
     - https://github.com/smallrye/smallrye-reactive-messaging/issues/334
- [x] Header support in message
     - Support and propagation of headers on message
     - https://github.com/smallrye/smallrye-reactive-messaging/issues/335

**Comment by emmanuelbernard** [comment]
@cescoffier Would be good to prioritize and define as phases at some point

**Comment by kenfinnigan** [comment]
Is the fault tolerance aspect specific to reactive messaging? It seems to be referring to just a "reactive" fault tolerance.

**Comment by cescoffier** [comment]
the patterns for pure reactive and reactive messaging are different. Here it refers to reactive messaging.

**Comment by kenfinnigan** [comment]
Is there a possibility to "coalesce" on a common core between them? So we don't duplicate the whole lot?

**Comment by cescoffier** [comment]
Probably, but maybe for 2 or 3 patterns (on failure resume, continue...), but lots of them are very messaging specifics. Also, it is not possible to reuse MP Fault Tolerance, as it's designed with (mostly synchronous) request-reply in mind.

**Comment by kenfinnigan** [comment]
I agree with the state of the current MP FT spec, but we're in the process of developing a new implementation that is intended to be more reactive. If there are specific requirements related to that then we should feed that back to @michalszynkiewicz & @Ladicek

**Comment by Markus-Schwer** [comment]
@cescoffier How far is the in-memory connector? I couldn't find any open or merged PR that looks like an in-memory connector.

**Comment by paulrobinson** [comment]
@emmanuelbernard, @cescoffier: I moved the remaining items form the Reactive Messaging section of the input document for consistency. Hopefully I didn't go against the intent of this issue.

I agree with @emmanuelbernard (above). I think this issue is too big to be one Epic. I would suggest breaking it down into smaller, related/collective pieces that can be actioned in one go. Given the amount of work in this issue, you might just want to just break out the Epics that will be actioned over the next 6 months or less.

**Comment by Ladicek** [comment]
I don't think I can 100% agree with the presentation of MP Fault Tolerance here, but I fully agree that FT in messaging is very much a different beast. As I don't know anything about MP Reactive Messaging, I don't feel qualified to judge if the same programming model (CDI interceptors, basically) could be applied.

**Comment by jglink** [comment]
Is there a timeline for the fault tolerance model integration?

We are currently investigating if we can use the Reactive Messaging integration in Quarkus for a new project and not having something like redelivery would be a no-go for it...

Thanks

**Comment by emmanuelbernard** [comment]
Pardon the noob question. I don't fully get fault tolerance for messaging. On the consumption side, just not ack before you're done seems to do the trick.
I suppose it is to have FT behaviors for sending messages?

**Comment by jglink** [comment]
That´s not quite the way it works for me on the receiver.
If I don´t ACK the message, the message is not delivered again. Only after I shutdown the Quarkus App and restart it, the message is read again.

**Comment by emmanuelbernard** [comment]
@cescoffier @kenfinnigan can we select what we want to do in the next 3-6 months concretely out of that list and create high level actions to put in the roadmap. 
Right now "Push forward reactive messaging needs" is not a description you would put in a changelog or an announcement blog. Let's make it more concrete.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/issues/9076 asks about RabbitMQ

**Comment by marcelorubim** [comment]
Hi!

This task is marked is done **Implement, test and integrate a JMS connector for reactive messaging**?

Any documentation on how to use JMS connector for Reactive Message? Looks like only AMQP, MQTT and Kafka are supported right now.

**Comment by kenfinnigan** [comment]
From a quick look, it doesn't appear to be an extension.

However, it should be possible to use it directly in JVM mode: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/jms/jms.html

**Comment by marcelorubim** [comment]
I tried to use this with Quarkus and got no luck.

Without the extension ```quarkus-smallrye-reactive-messaging```, the application does not start.

And when I try to use the configuration for the JMS connector, this exception is thrown:

```
18:25:56 ERROR [io.qu.application] (Quarkus Main Thread)  Failed to start application: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalArgumentException: SRMSG00072: Unknown connector for `prices`.
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:22)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)

```

I'll check the effort make an extension for this.

**Comment by cescoffier** [comment]
Closing this epic. All the tasks have been done.
