### ISSUE TITLE
OIDC adapter core improvements

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5867]
### Description
OIDC adapter core improvements to do with the in demand multi-tenancy feature, production ready logout support and loading JWK sets on demand to support the rotation have to be done.

### Analysis
A complete [list of the OIDC issues](https://github.com/quarkusio/quarkus/issues?q=is%3Aissue+is%3Aopen+label%3Aarea/oidc).

### Tasks
- [x] Multi-tenancy support (#4448)
- [x] Enhanced logout support (#4481)
- [x] Load JWK keys on demand (#5003)

**Comment by emmanuelbernard** [comment]
@sberyozkin What will happen in the next 3-6 months?

**Comment by sberyozkin** [comment]
@emmanuelbernard sorry for a delay, logout feature is now supported (with few minor related issues to follow). I've dropped a couple of issues from this epic which I thought were not very critical. I'm going to work on the Vertx OAuth2 PRs very shortly to get #5003 fixed

**Comment by emmanuelbernard** [comment]
Should it be part of the 6 months roadmap epics?

**Comment by sberyozkin** [comment]
@emmanuelbernard Hi, last issue fixed for 1.6.0, so the epic is finally resolved :-)
