### ISSUE TITLE
OIDC adapter stabilization

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5874]
### Description
Users are actively experimenting with the OIDC adapter and have reported a number of bugs.

### Analysis
A complete [list of the OIDC issues](https://github.com/quarkusio/quarkus/issues?q=is%3Aissue+is%3Aopen+label%3Aarea/oidc).

### Tasks
- [x] OIDC `web-app` applications do not work with IdentityServer 4 (#6087, depends on #6526)
- [x] OIDC `web-app` applications do not work with Okta (#5277, depends on #6526)
- [x] OIDC `web-app` applications do not work with Microsoft ADFS (#6603, depends on #6526)
- [x] `quarkus-keycloak-authorization` does not work with reactive routes (#5809)
- [x]  `integration-tests/oidc-code-flow` test is unstable (#5926)
- [x] OIDC `web-app` applications have to support a static `redirect-url` (#5733)
- [x] OIDC `web-app` applications do not work with Auth0 (#5829)
- [x] `quarkus-keycloak-authorization` does not work with Keycloak 8 (#5868)
- [x] HTTP 403 should be reported if token has no expected custom role claim (#5750)
- [x] `quarkus-keycloak-authorization` claim information point read body NPE (#5959)

**Comment by paulrobinson** [comment]
@sberyozkin Are you the Epic lead for this? See here for an explanation of the role: https://github.com/quarkusio/quarkus/wiki/High-Level-Planning-Process#ive-been-assigned-an-epic-what-do-i-need-to-do.

If so, can you assign this issue to yourself? Thanks :-)

**Comment by sberyozkin** [comment]
@paulrobinson sorry, just got back from a trip home...

**Comment by sberyozkin** [comment]
I've removed `KeycloakAdminClient does not work because it depends on RestEasy 3.x (#6350)` from this Epic because it is technically not related to both `quarkus-oidc` and `quarkus-keycloak-authorization`
