### ISSUE TITLE
Document and Extend dev mode to be more accessible/integrated with existing tools

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5917]
### Description
devmode currently rely on a mixture of source and built file change detection. For now it is mainly looking at source changes which means it relies on having build tools available on the same host/container. 

We should document and if needed extend/adopt devmode to fit into existing technologies especially if we can avoid requiring build tools on the same host/container as where the app is running. 

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

#### (document) source dev-mode
Current dev-mode (and remote-dev) is based on source file changes being detected. This means any existing rsync based tool like oc, odo, fmp watch, jboss tools, vscode, potentially skaffold.dev etc. should work more or less out of the box with quarkus dev-mode running on a remote host and you just do changes locally to then have the source files updated  

#### Binary (exploded) dev-mode
Source dev-mode has many advantages but also limits:
a) Changes are not persisted between starts/reconnects
b) Does not utilize the fact a developers machine probably already compiled and fetch the exact class or jar file necessary 
c) Requires the host to have build tools (maven/gradle) available to build/compile the sources
d) Can’t be run directly from an IDE

Is solved by actually rsyncing source changes over, dev-mode could possibly just save it directly when invoked via remote-dev requests.
To help on b) we should enable or possibly by default have dev-mode listen to binary artifacts updates in addition to source updates. Then when an “rsync” happens quarkus does not need to do anything but to do the restart/reload.
c) requires we can do devmode without requiring gradle/mvn plugins. This would allow us to add it to a future quarkus cli but also possibly run it directly from an IDE.   

### Tasks
- [ ] document use of current source dev mode when using rsync
- [ ] ensure devmode will pick up binary/built changes without corresponding source changes
- [ ] enable devmode to run from cli (gradle/maven should not be a requirement except for build/pom.xml changes.
- [ ] check & document integration works with vscode remote dev mode
- [ ] work with odo team on enabling quarkus (any rsync) friendly mode
- [ ] check & document integration works with skaffold.dev
- [ ] check & document integration with jbosstools server adapter
- [ ] check & document integration with intellij 
 
-

**Comment by maxandersen** [comment]
@stuartwdouglas fyi  - can you outline your thoughts on how feasible a binary-exploded mode  would be possible ?

**Comment by emmanuelbernard** [comment]
Action for the next 3-6 months? @maxandersen ?

**Comment by maxandersen** [comment]
yes, I would like to see some movement on this - pinged @stuartwdouglas on the feasibility of it since to make quarkus really "fit in" to these existing workflows and be simple to setup we do need quarkus devmode to be a bit more complex to allow reload from changed classes/resources rather do a full mvn/gradle compile on change.

**Comment by stuartwdouglas** [comment]
So bits of this are more complex than others. It is really simple to make the existing dev mode work with binary changes, as the current dev mode is a two stage process (compile, then check for changed .class files), we can essentially just skip phase 1.

If you want to take a production mode image and run it in remote dev mode then this is a bit more involved.
