### ISSUE TITLE
Clickable stacktraces

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5918]
### Description
in devmode we have reversible stacktraces which are really nice but would it not be nice to have them be clickable and open up your local editor.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ] add copy to clipboard for stacktrace block (to use in IDE's that can understand stacktraces)
- [ ] implement client side parsing/highlighting of stacktrace block
- [ ] add end point only available to trigger opening local editor identified with EDITOR / QUARKUS_DEVMODE_EDITOR on file / line number info (would need to be protected against remote access)
- [ ] possibly link directly to editors, i.e. intellij has localhost open file ability
- [ ] possibly link to che.openshift.io

**Comment by gsmet** [comment]
My understanding is that Stuart did something like that which works with some IDEs.

**Comment by maxandersen** [comment]
@stuartwdouglas do I need to do something special to enable it ? this is what I get in 2.6.1 with an exception thrown in rest easy handler.

<img width="1466" alt="2022-01-02_07-53-13" src="https://user-images.githubusercontent.com/54129/147868586-a4d9bf4b-8b44-4b3c-abe6-1afd50782526.png">

**Comment by gsmet** [comment]
I think it was done in the console, not in the UI, which makes kinda sense given you have to execute a local binary.

**Comment by maxandersen** [comment]
yeah so the console one is not this issue. This was specifically about highlighting in the browser as the one in console requires you to move/change focus and won't necessarily stay around as long as the browser is open. 

I found the "opens last exception in IDE" and doesn't seem to work for my setup at least - but that's a separate issue I've opened at https://github.com/quarkusio/quarkus/issues/22574

**Comment by gsmet** [comment]
Well then please adjust the title of the issue.

Thanks.
