### ISSUE TITLE
Kubernetes / OpenShift zero-config/install operation 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5920]
### Description
With fmp/jkube maven/gradle plugins and dekorate we have the opportunity to provide a initial experience with openshift/kubernetes that literally only require account credentials for a cluster. 

we should make that happen while having a gradual way of allowing users to configure/expand to use full features of other tools.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ] POC of kubernetes/openshift build/deploy via kubernetes extension github.com/quarkusio/quarkus/pull/5496
- [ ] check and document how users will customize via jkube/dekorate 
- [ ] check and document how it works with odo 
- [ ] check and document how users will customize via kustomize
- [ ]  check and document how works with skaffold.dev

**Comment by jclingan** [comment]
One interesting use case that came up at KubeCon is that some organizations (banks, Gov) don't allow  Docker on the desktop. If this could be done in a manner that that did not require a local docker registry it would address the needs of more secure environments.

**Comment by gunnarmorling** [comment]
Might be provided via https://github.com/quarkusio/quarkus/issues/6007

**Comment by maxandersen** [comment]
@jclingan #6007 talks about generating the container - you'll still need a registry to push to from whereever you build and then pull from it where you want to run it. With this you can do the build but still can't run it...

**Comment by emmanuelbernard** [comment]
Hey @maxandersen I'm working on the roadmap and I think this one needs work.
Can we consider it closed, should we create a different epic for the work we want to do in the next 3-6 months?

**Comment by gattytto** [comment]
the best would be an OCI compliant runtime for CRI-O, like [gVisor](https://github.com/google/gvisor) could I sugest qVisor?

**Comment by geoand** [comment]
I added checkboxes to what has already been done.

**Comment by maxandersen** [comment]
@geoand @iocanel the one "big thing" missing in this is to have it working with but not needing kubectl/oc/docker to authenticate/build - how far are we actually from that ? can we pass in username/passwords or in case of missing kubeconfig credentials do the login and update the kubeconfig for future operations ?

**Comment by geoand** [comment]
We don't have that AFAIK. 
@iocanel the client can do that can't it? So it's just of matter of supplying the proper Quarkus configuration, right?

**Comment by iocanel** [comment]
The client can use raw token for Kubernetes and Openshift. Also is able to
use username/password for Openshift.

For docker authentication, build and push we have lot of options. Maybe
Rohan and Marc can help with that.

**Comment by emmanuelbernard** [comment]
@maxandersen @iocanel and friends, what shoudl we target this for 1.6 or later?

**Comment by emmanuelbernard** [comment]
@maxandersen ping the pinger

**Comment by n1hility** [comment]
@maxandersen should we call this complete?

**Comment by iocanel** [comment]
For kubernetes and openshift we are ok, but we won't update the
.kube/config. For docker though there are two things that are missing:

- we use the docker binary under the hood.
- we  require a . docker/config.json

The latter is possibly true for job too.

Let me pick this up.
