### ISSUE TITLE
One universe with multiple platforms

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5962]
### Description
in 1.0 we released one universal platform; this epic is gathering the tasks/features needed to cleanup/expand the notion of platform.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [ ] define version compatibility setup
- [ ] bom-less add/remove extension

## Epic items
(this section is auto-generated - manual edits will get lost)
- [ ] [#9592](https://github.com/quarkusio/quarkus/issues/9592) Have a catalog to describe community quarkus extensions  with and without a platform
- [ ] [#9593](https://github.com/quarkusio/quarkus/issues/9593) Add initial implementation of list/add/remove extension utilizing registry
- [ ] [#4361](https://github.com/quarkusio/quarkus/issues/4361) document quarkus-extension.yaml
- [ ] [#4319](https://github.com/quarkusio/quarkus/issues/4319) Document what it takes to be added to the platform
- [ ] [#9294](https://github.com/quarkusio/quarkus/issues/9294) Registry for extensions and platforms
- [x] [#8163](https://github.com/quarkusio/quarkus/issues/8163) Implement the flow of GitHub Action jobs reporting Quarkus Platform readiness
- [ ] [#8134](https://github.com/quarkusio/quarkus/issues/8134) Allow extensions to influence newly generated apps: codenamed "CodeStarts"

**Comment by nimo23** [comment]
**one question about:**

>consider introducing extensions.quarkus.io or similar as a true open registry of quarkus extensions (think npm.org, rubygems.org, herd.ceylon.org, etc.)

Is this really makeable without having a _module system in quarkus_ (such as, `jboss modules` or `JSR-376`)? For example, think of not conflicting (transitive) dependencies, etc.

**Comment by maxandersen** [comment]
> Is this really makeable without having a _module system in quarkus_ (such as, `jboss modules` or `JSR-376`)? For example, think of not conflicting (transitive) dependencies/extensions, etc.

For this I'm not really talking about having a full blown module system; but more an extension system - maybe a better analogy is a "marketplace" like vscode, eclipse, intellij marketplace - its about having a place where the quarkus extensions are possible to find, links to documentation, etc.

**Comment by emmanuelbernard** [comment]
@maxandersen can you refresh / nuke based on what we want to achieve in the next 3 to 6 months

**Comment by maxandersen** [comment]
added the "leftovers" so using this as the "hub" for platform work.

**Comment by emmanuelbernard** [comment]
@maxandersen find a better name

**Comment by n1hility** [comment]
This is more or less Quarkiverse, so closing to be replaced with other subtasks as needed.
