### ISSUE TITLE
Adapt code.quarkus.io to the future registry.quarkus.io

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5963]
### Description
Various highlevel features for code.quarkus.io

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [x] [push generated project to github](https://github.com/quarkusio/code.quarkus.io/pull/227
)
- [x] [shorten url](https://github.com/quarkusio/code.quarkus.io/pull/178) (require storage)  
- [X] Add backend analytics (https://github.com/quarkusio/code.quarkus.io/pull/191)
- [ ] Add tags to help search
- [ ] Make exentions display more info and improve descriptions (git readme, examples, guides, etc.) to be more useful for users and recognize extension contributors (see #5962 extension registry)
- [ ] store extension metrics in storage (for popularity indicators)
- [x] Improve mobile experience
- [ ] Support multiple platforms (community vs product, latest vs stable, variations)..

**Comment by emmanuelbernard** [comment]
can we refresh nuke and hair cut based on what we want to do in the next 3-6 months?
Also "foo improivement" is too vague which makes it hard to mvoe between roadmap columns. Better be more specific.

**Comment by maxandersen** [comment]
@ia3andy can you refresh this with what is done ? 

i think multiple platform is the one big missing.

**Comment by emmanuelbernard** [comment]
@maxandersen change title and refresh to specify its the multi platform search 
Also related to tools querying the BOM

**Comment by emmanuelbernard** [comment]
@ia3andy @maxandersen if you don't give a better name and a target release in the roadmap to this card, I'll simply close it in 48 hours.

**Comment by ia3andy** [comment]
@maxandersen it seems that we can close this? most of it would now be covered by the registry, code.quarkus.io would just have to adapt to it?

**Comment by ia3andy** [comment]
I think we should create a new issues if things in here are still something..
