### ISSUE TITLE
Metrics support for 50% of the relevant extensions

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#6196]
### Description
Provide metrics from various extensions

### Analysis
See the documentation in the initial PR (https://github.com/quarkusio/quarkus/pull/5272)

### Tasks
- [x] Initial work with common infrastructure for metrics from extensions (PR https://github.com/quarkusio/quarkus/pull/5272/)
- [x] Agroal (included in initial PR https://github.com/quarkusio/quarkus/pull/5272/)
- [ ] Vert.x (https://github.com/quarkusio/quarkus/issues/2027)
- [x] Hibernate ORM (https://github.com/quarkusio/quarkus/issues/6193)
- [x] RESTEasy (https://github.com/quarkusio/quarkus/issues/6220)
- [ ] SmallRye Reactive Messaging (https://github.com/quarkusio/quarkus/issues/3113)
- [x] SmallRye Fault Tolerance
- [x] Jaeger
- [x] Infinispan (We might want to explore the possibility to strip away the `smallrye-metrics` dependency in cases when metrics are not needed, but other than that, it seems to work well. Infinispan itself provides this by using MP Metrics API)
- [ ] Kafka Streams
- [ ] MongoDB 
- [ ] Kogito

.. more to be added over time where deemed appropriate, feel free to suggest in comments

**Comment by jmartisk** [comment]
I suppose we've covered the basic extensions, more will be coming as appropriate, for example Vert.x.
SmallRye Reactive Messaging will have metrics soon too.
Let's close this one.
