### ISSUE TITLE
GraalVM issues to track for 1.2 / 19.3

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6222]
- [X] https://github.com/oracle/graal/issues/1966 - NPE in BootLoader.hasClassPath() - worked around with substitutions - fixed in 19.3.0.2, workaround reverted here: https://github.com/quarkusio/quarkus/pull/6364
- [ ] https://github.com/oracle/graal/issues/1889 - unusable API Version - we decided to not use this for now
- [X] https://github.com/oracle/graal/issues/1927 - DynamicProxySupport is not thread safe - fixed in 19.3.0.2
- [ ] https://github.com/oracle/graal/issues/1883 - NullPointerException during security services registration - worked around
- [X] https://github.com/quarkusio/quarkus/issues/6127 - BootLoader.loadClassOrNull() NPE - worked around with substitutions - fixed in 19.3.0.2, workaround reverted here: https://github.com/quarkusio/quarkus/pull/6364
- [X] https://github.com/quarkusio/quarkus/issues/6115 https://github.com/oracle/graal/issues/1995 - Neo4j doesn't work in native mode anymore - fixed in 19.3.0.2
- [ ] https://github.com/oracle/graal/issues/1984 https://github.com/quarkusio/quarkus/issues/6136 - RSS regression with 1.1.0.CR1 and GraalVM 19.3.0
- [ ] https://github.com/oracle/graal/issues/1971#issuecomment-571203467 - Camel Quarkus beans IT not working - still reproducible with 19.3.0.2

**Comment by thomaswue** [comment]
Issues https://github.com/oracle/graal/issues/1995 and https://github.com/oracle/graal/issues/1927 are mentioned as fixed in 19.3.0.2 release notes. Other issues seem closed except for https://github.com/oracle/graal/issues/1984 (where a JDK backport fix into 8u is proposed by @adinn). Let us know if there are other issues to consider or issues to reopen @emmanuelbernard.

**Comment by machi1990** [comment]
> Issues [oracle/graal#1995](https://github.com/oracle/graal/issues/1995) and [oracle/graal#1927](https://github.com/oracle/graal/issues/1927) are mentioned as fixed in 19.3.0.2 release notes. 

I have opened a draft PR #6364 to update the Graal version and add neo4j IT tests in CI. 
/cc @gsmet @gwenneg @michael-simons

**Comment by emmanuelbernard** [comment]
Thanks @thomaswue Looking at oracle/graal#1984, I see the following actions:

- [ ] @johnaohara to double check the JDK 11 memory usage. In his tests, JDK 11 was having a similar "extra" memory usage as JDK 8 which does not match the reading of the code and proposed backport of the patch from 11 to 8.
    - if the extra memory for JDK 11 is confirmed, then we are back to square 1 having to find a short term solution for SubstrateVM
- [ ] @adinn do you know when the JDK 8 backport would be in? 8u242 or 8u252? Considering https://wiki.openjdk.java.net/display/jdk8u/Main dates and that I don't see the patch on http://hg.openjdk.java.net/jdk8u/jdk8u/ I imagine it to be more 8u252 which puts it as GA April 15th

I see the following branches for our future
- a. JDK 11 is reasonable in memory usage and we baseline Quarkus on 11 dropping Java 8 support. _Quarkus 1.2 adopts GraalVM 19.3_.
- b. JDK 11 is reasonable in memory usage, we recommend people to use Graal 19.3 for JDK 11 and 19.2 for JDK 8. AFAIK, this is not trivial and might not be possible because of some graalvm package name changes that happened between 19.2 and 19.3 CC @gsmet @gwenneg. _Quarkus 1.2 adopts GraalVM 19.3_.
- c. Quarkus does not drop JDK 8 support and the double support of GraalVM 19.2/19.3 is not possible => _Quarkus waits for April 15th+ to upgrade to GraalVM 19.3_
- d. JDK 11 shows the same > 20MB memory usage for the CRUD app. _Quarkus waits for a solution on GraalVM 19.3+ to reach back 20MB memory usage for the CRUD app._

Am I missing a future?
@n1hility do you see any alternative?

**Comment by adinn** [comment]
@emmanuelbernard jdk8u is currently frozen pending release of 8u242. I prepared and successfully tested the backport and posted an RFR today asking to push to the jdk8u-dev tree. So, it ought to be available in  u252 released in early April.

**Comment by gsmet** [comment]
@thomaswue so to keep you in the loop, most issues are fixed **except**:

 * the RSS usage regression which is blocking for us, see @adinn and @emmanuelbernard 's comments above
 * Camel Quarkus ITs failing with `/usr/bin/ld: /opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/java/lang/reflect/Proxy.c:97: undefined reference to `VerifyFixClassname'`  - see https://github.com/oracle/graal/issues/1971#issuecomment-571203467 where I posted a (hopefully straightforward) way to reproduce it

Thanks.
