### ISSUE TITLE
Clements s2i soapbox

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6677]
### Description
list of issues/open concerns around the s2i build approach

- [ ] _ quarkus fat jar approach not fitting well with s2i and workaround is marked [deprecated](https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/.s2i/environment) and issue still [open on it](url)
- [ ] _ concerns about "agent bond and all this stuff" in s2i (@cescoffier can you elaborate)
- [ ] _ where is the actual source of s2i java image builders ? is https://github.com/jboss-openshift/cct_module/tree/master/jboss/container/java/s2i/bash the right one ? 
  * would need to disable somehow hawkular and jolokia.
- [ ] _ we need an s2i that:
  - allows us to copy more than just a fat jar, without relying on deprecated features
  - do not force usage of java agent (bond, jolokia...)
  - allow the user to pass JAVA_OPTS and APP_OPTS
  - build the application with a recent enough version of Maven.

**Comment by maxandersen** [comment]
s2i we don't want to use: https://github.com/fabric8io-images/s2i/blob/master/java/templates/s2i/run#L43 as it assumes spring boot inlogs etc.

**Comment by cescoffier** [comment]
I love the title of this issue (that I'm just discovering). I think we should clarify our strategy around:

1. container creation
2. kubernetes deployment (including OpenShift)

Based on this, we can decide what needs to be done for this issue.

**Comment by geoand** [comment]
With s2i pretty dead, should we close this?

**Comment by cescoffier** [comment]
it is still used...

**Comment by geoand** [comment]
Sure, but do we really plan on improving our support for it?

**Comment by cescoffier** [comment]
No :-D

**Comment by geoand** [comment]
So let's close :)
