### ISSUE TITLE
Introducing Mutiny

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#7097]
### Description
The objective of this epic is to gather all the tasks related to the introduction of Mutiny in Quarkus, as well as the deprecation of Axle and RX APIs, documentation and quickstart updates...

### Tasks
- [X] Create the Mutiny extension - https://github.com/quarkusio/quarkus/pull/7098
- [X] Integrate Mutiny in the Vert.x extension, and manage Axle / RX deprecation - https://github.com/quarkusio/quarkus/pull/7098
- [X] Integrate Mutiny with `@ConsumeEvent` - https://github.com/quarkusio/quarkus/pull/7098
- [x] Integrate Mutiny with RestEasy - https://github.com/quarkusio/quarkus/pull/7177
- [x] Integrate Mutiny with Context propagation - https://github.com/quarkusio/quarkus/pull/7303
- [x] Update Vert.x quickstart to use Mutiny instead of Axle - #7388 
- [X] Integrate Mutiny in Qute - https://github.com/quarkusio/quarkus/pull/7101
- [x] Update the mailer extension as well as the guide - https://github.com/quarkusio/quarkus/pull/7211
- [x] Integrate the Mutiny API with the PostGreSQL and MySQL reactive client - this includes updating the guide - https://github.com/quarkusio/quarkus/pull/7216
- [x] Integrate Mutiny API in the reactive Mongo API - https://github.com/quarkusio/quarkus/pull/7263
- [x] Write a Mutiny quickstart
- [x] Integrate Mutiny Verticle - https://github.com/quarkusio/quarkus/pull/7231
- [x] Add Uni and Multi support to Reactive Messaging -    _partially done_
- [x] Switch Mail Qute template support to Mutiny 
- [x] Update Panache Mongo (reactive version) to provide a Mutiny API #7327 
- [x] Use Mutiny API in Quarkus Security

**Comment by loicmathieu** [comment]
@cescoffier it's still time for MongoDB with Panache to replace the Axle base implementation to a Mutiny one, I can do it easily.

Provinding both implementation is more works (the deployment part of MongoDB with Panache is complexe).

I can work on it this week based on your mongodb-client branch, my only question is do we expose Uni/Multi or do we stick with CompletionStage/Publisher ?

**Comment by cescoffier** [comment]
@loicmathieu ideally both. In your Panache code, the Axle model is in the `axle` package. Just create the mutiny one in the `reactive` package.

So:

1. Deprecate `io.quarkus.mongodb.panache.axle.ReactivePanacheMongoEntity`
2. Create `io.quarkus.mongodb.panache.reactive.ReactivePanacheMongoEntity`

**Comment by loicmathieu** [comment]
@cescoffier the Axle implementation was merged a few days ago so nobody already used it. So we can still replace it. Having a new thing already deprecated seems strange ...

**Comment by emmanuelbernard** [comment]
@cescoffier I'll move this out of the roadmap board as the remaining tasks are more focused now. We could create a more specific subsequent epic if you feel it needs visibility at the roadmap level

**Comment by cescoffier** [comment]
All Done!
