### ISSUE TITLE
Allow extensions to influence newly generated apps: codenamed "Codestarts"

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#8134]
### Description
We need a way to generate different project depending on the selected extensions.
We should have example codes showing the different features of the extensions.

### Core

- code: https://github.com/quarkusio/quarkus/tree/master/independent-projects/tools/codestarts
- core codestarts dir: https://github.com/quarkusio/quarkus/tree/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core

### Contributing an example Codestart

- doc: https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/codestarts/README.adoc
- codestarts dir: https://github.com/quarkusio/quarkus/tree/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/examples

### Tasks

- [x] Phase 1 (#8178): 
  - [x] Refactor the current codegen (#9609, #9631, #9787)
  - [x] Design and Implement the base Codestart logic to give the same level of functionality as the current codegen and plug it to the tooling as an experimental way of generating Quarkus projects (#10372). 
- [x] Phase 2 (wip): 
  - [x] Add new codestarts based on the most important existing quickstarts and improve the API/Model. 
  - [x] Make it the default way of generating Quarkus projects: #12473
- [ ] Phase 3: Until then the codestarts were located in Quarkus core to keep everything together and make it easy to change the API/Model, In phase 3 we move them to the related extensions. **This is going to need some new logic to resolve them before generating the project.**

### Issues:
https://github.com/quarkusio/quarkus/labels/area%2Fcodestarts

**Comment by ia3andy** [comment]
Until then, you can use the different quickstarts we provide: https://github.com/quarkusio/quarkus-quickstarts/
Also we have several guides which could help you: https://quarkus.io/guides/

**Comment by emmanuelbernard** [comment]
@ia3andy can you figure our whether you want to close this one or #1940 and add the surviving one to the roadmap board?

**Comment by Dufgui** [comment]
Could I help on this ?

**Comment by n1hility** [comment]
@ia3andy should we call this done and maintain additional extensions as separate issues?
