### ISSUE TITLE
List of TODO for public release

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#902]
### Meta issue to track all stuff that needs to be done for the final push-to-open

- [x] get GitHub org
- [x] Create public zulip org
- [x] decide if we keep history or not (Emmanuel wants history as it shows we did not poop this one out in a week)
- [x] Set public zulip org
- [x] Run first request boot time and RSS usage for us vs HotSpot us vs major competitors in same application
- [x] All stuff in `/independent-projects` published (and tagged) separately
- [x] Have new codestyle applied
- [x] Full rename of project: modules, packages, comments, docs
- [x] Apply full-rename treatme to quickstarts too
- [x] Move the github repositories to its own organization
- [x] Get organization on OSS Sonatype and get a few users in (requires the web site first)
- [x] Switch to an OSS Maven repository for publishing
- [x] Make sure that the generated projects are fine
- [x] Update release scripts
- [x] Select the Twitter and GitHub handles as IO or HQ or some of the other proposals

### Nice to have:

- [ ] CI results to be public
- [x] Rewrite the documentation, double check all references have been updated
- [x] Rewrite all quickstarts, replace references, double check
- [ ] StackOverflow tags
- [ ] Update documentation sections to follow quickstart style

### Soon after:
- [ ] Cleanup old repositories https://github.com/jbossas?q=protean
- [ ] Kill the private Nexus instance

**Comment by kenfinnigan** [comment]
Wondering if this should be closed now? @n1hility @emmanuelbernard
