### ISSUE TITLE
Improve gRPC support

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9264]
Clement internal wish: Quarkus 1.7 / 1.8

* [x] - #9324 - Compressor support
* [ ] - #9325 - Name resolver support
* [ ] - #9326 - Load balancer support 
* [x] - #9327 - hot reload on RPC request 
* [x] - #9328 - hot reload on `proto` file change
* [ ] - #9329 - control flow integration

**Comment by emmanuelbernard** [comment]
@michalszynkiewicz @cescoffier let's write down what that means and what value this brings.

**Comment by cescoffier** [comment]
* Hot reload support (even when modifying the proto file)
* Compressor support
* Proper implementation of the back-pressure protocol

**Comment by michalszynkiewicz** [comment]
What about e.g. load balancer support?

**Comment by cescoffier** [comment]
Yes, let me add that too.

**Comment by cescoffier** [comment]
I've added in the issue description the individual issues.

**Comment by parkee** [comment]
I noticed currently grpc calls don't propagate tracing context (jaeger or b3 headers).
I suppose that also should be added to the list of improvements.

Is there a way to work around that at this time and manually add support for tracing?

**Comment by michalszynkiewicz** [comment]
@pavolloffay what do you think about tracing context for grpc calls ^

**Comment by pavolloffay** [comment]
+1

**Comment by michalszynkiewicz** [comment]
@parkee could you create an issue and we will discuss with @cescoffier when he's back from PTO if we want it here or separately?

**Comment by parkee** [comment]
Sure @michalszynkiewicz 
#11059

**Comment by n1hility** [comment]
@michalszynkiewicz @cescoffier should we split this issue into 1.8 and 1.9? It looks like we aren't going to get to everything in time for 1.8

**Comment by cescoffier** [comment]
The remaining issues are mostly going to be 1.9 / 1.10.

**Comment by cescoffier** [comment]
@michalszynkiewicz do you prefer keeping this epic or create individual issues?

**Comment by michalszynkiewicz** [comment]
we already have individual tasks, don't we?
I'm okay with closing this, I'm focusing on tasks anyway.
