### ISSUE TITLE
Improve GraalVM 20.1 support

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9796]
**Description**
Follow up for #9297 

## Epic items
(this section is auto-generated - manual edits will get lost)
- [x] [#9792](https://github.com/quarkusio/quarkus/issues/9792) Offer quarkus property to enable debug symbols
- [ ] [#9794](https://github.com/quarkusio/quarkus/issues/9794) Add job to test `-H:+RemoveSaturatedTypeFlows` and `-H:+PrintAnalysisStatistics`
- [ ] [#9795](https://github.com/quarkusio/quarkus/issues/9795) Consider --install-exit-handlers (GraalVM 20.1)
